export type ArchiveDefault = true | false | "optional";
export type ReferenceDefault = true | false | "optional";

export type JobdeskCategoryRule = {
  categoryKey: string;
  categoryLabel: string;
  subcategoryKey: string;
  subcategoryLabel: string;
  outputTypes: string[];
  archiveDefault: ArchiveDefault;
  referenceDefault: ReferenceDefault;
  requiresFile: boolean | "optional";
  requiresSourceLink: boolean | "optional";
  sensitivity: "normal" | "internal" | "sensitive";
  notes?: string;
};

export const MAIN_CATEGORIES = [
  { key: "desain_publikasi", label: "Desain Publikasi" },
  { key: "identitas_acara_dan_panitia", label: "Identitas Acara dan Panitia" },
  { key: "dokumen_administrasi", label: "Dokumen Administrasi" },
  { key: "keuangan_dan_spreadsheet", label: "Keuangan dan Spreadsheet" },
  { key: "konten_dan_copywriting", label: "Konten dan Copywriting" },
  { key: "video_dan_multimedia", label: "Video dan Multimedia" },
  { key: "dokumentasi_foto", label: "Dokumentasi Foto" },
  { key: "aset_desain", label: "Aset Desain" },
  { key: "perlengkapan_dan_operasional", label: "Perlengkapan dan Operasional" },
  { key: "koordinasi_dan_aktivitas_non_file", label: "Koordinasi dan Aktivitas Non-File" },
  { key: "publikasi_dan_media_sosial", label: "Publikasi dan Media Sosial" },
  { key: "registrasi_dan_peserta", label: "Registrasi dan Peserta" },
];

export const CATEGORY_RULES: JobdeskCategoryRule[] = [
  // 1. Desain Publikasi
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "poster",
    subcategoryLabel: "Poster",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Cocok untuk referensi desain",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "pamflet",
    subcategoryLabel: "Pamflet",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Cocok untuk referensi desain",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "flyer",
    subcategoryLabel: "Flyer",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Cocok untuk referensi desain",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "feed_instagram",
    subcategoryLabel: "Feed Instagram",
    outputTypes: ["image", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Desain feed media sosial",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "story_instagram",
    subcategoryLabel: "Story Instagram",
    outputTypes: ["image", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Berguna untuk referensi template story",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "reels_cover",
    subcategoryLabel: "Reels Cover",
    outputTypes: ["image", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Desain cover video pendek",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "thumbnail_video",
    subcategoryLabel: "Thumbnail Video",
    outputTypes: ["image", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Desain cover YouTube/highlight",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "banner_digital",
    subcategoryLabel: "Banner Digital",
    outputTypes: ["image", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Desain banner landscape digital",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "spanduk_banner_cetak",
    subcategoryLabel: "Spanduk / Banner Cetak",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Desain spanduk fisik",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "x_banner",
    subcategoryLabel: "X-Banner",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Desain standing banner cetak",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "baliho",
    subcategoryLabel: "Baliho",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Desain cetak baliho besar",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "twibbon",
    subcategoryLabel: "Twibbon",
    outputTypes: ["image", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Biasanya format PNG transparan",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "frame_foto",
    subcategoryLabel: "Frame Foto",
    outputTypes: ["image", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Overlay frame dokumentasi",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "photobooth",
    subcategoryLabel: "Photobooth",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Layout desain photobooth fisik",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "background_zoom",
    subcategoryLabel: "Background Zoom",
    outputTypes: ["image", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Resolusi landscape 16:9",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "countdown_design",
    subcategoryLabel: "Countdown Design",
    outputTypes: ["image", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Desain hitung mundur event",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "announcement_design",
    subcategoryLabel: "Announcement Design",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Desain pengumuman hasil",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "thank_you_post",
    subcategoryLabel: "Thank You Post",
    outputTypes: ["image", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Desain ucapan penutup acara",
  },

  // 2. Identitas Acara dan Panitia
  {
    categoryKey: "identitas_acara_dan_panitia",
    categoryLabel: "Identitas Acara dan Panitia",
    subcategoryKey: "name_tag",
    subcategoryLabel: "Name Tag",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Identitas peserta/panitia",
  },
  {
    categoryKey: "identitas_acara_dan_panitia",
    categoryLabel: "Identitas Acara dan Panitia",
    subcategoryKey: "id_card",
    subcategoryLabel: "ID Card",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Kartu panitia/crew",
  },
  {
    categoryKey: "identitas_acara_dan_panitia",
    categoryLabel: "Identitas Acara dan Panitia",
    subcategoryKey: "kartu_panitia",
    subcategoryLabel: "Kartu Panitia",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Versi lokal name tag",
  },
  {
    categoryKey: "identitas_acara_dan_panitia",
    categoryLabel: "Identitas Acara dan Panitia",
    subcategoryKey: "badge_peserta",
    subcategoryLabel: "Badge Peserta",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Identitas delegasi/peserta",
  },
  {
    categoryKey: "identitas_acara_dan_panitia",
    categoryLabel: "Identitas Acara dan Panitia",
    subcategoryKey: "sertifikat",
    subcategoryLabel: "Sertifikat",
    outputTypes: ["image", "pdf", "canva_link", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: "optional",
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Template sertifikat sangat penting",
  },
  {
    categoryKey: "identitas_acara_dan_panitia",
    categoryLabel: "Identitas Acara dan Panitia",
    subcategoryKey: "piagam",
    subcategoryLabel: "Piagam",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Desain piagam pemenang/mitra",
  },
  {
    categoryKey: "identitas_acara_dan_panitia",
    categoryLabel: "Identitas Acara dan Panitia",
    subcategoryKey: "plakat_design",
    subcategoryLabel: "Plakat Design",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Desain plakat/cenderamata",
  },
  {
    categoryKey: "identitas_acara_dan_panitia",
    categoryLabel: "Identitas Acara dan Panitia",
    subcategoryKey: "kop_surat_acara",
    subcategoryLabel: "Kop Surat Acara",
    outputTypes: ["image", "document", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Kop surat resmi kepanitiaan",
  },
  {
    categoryKey: "identitas_acara_dan_panitia",
    categoryLabel: "Identitas Acara dan Panitia",
    subcategoryKey: "logo_acara",
    subcategoryLabel: "Logo Acara",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Logo utama event",
  },
  {
    categoryKey: "identitas_acara_dan_panitia",
    categoryLabel: "Identitas Acara dan Panitia",
    subcategoryKey: "maskot_acara",
    subcategoryLabel: "Maskot Acara",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Maskot/karakter event",
  },
  {
    categoryKey: "identitas_acara_dan_panitia",
    categoryLabel: "Identitas Acara dan Panitia",
    subcategoryKey: "brand_guideline_acara",
    subcategoryLabel: "Brand Guideline Acara",
    outputTypes: ["pdf", "canva_link", "figma_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Panduan identitas visual",
  },
  {
    categoryKey: "identitas_acara_dan_panitia",
    categoryLabel: "Identitas Acara dan Panitia",
    subcategoryKey: "color_palette",
    subcategoryLabel: "Color Palette",
    outputTypes: ["image", "canva_link", "figma_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Kode warna branding",
  },
  {
    categoryKey: "identitas_acara_dan_panitia",
    categoryLabel: "Identitas Acara dan Panitia",
    subcategoryKey: "supergraphic",
    subcategoryLabel: "Supergraphic",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Elemen grafis dekoratif",
  },

  // 3. Dokumen Administrasi
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "proposal",
    subcategoryLabel: "Proposal",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Template proposal kegiatan",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "cover_proposal",
    subcategoryLabel: "Cover Proposal",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Desain cover depan proposal",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "lpj",
    subcategoryLabel: "LPJ",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Template laporan pertanggungjawaban",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "surat_undangan",
    subcategoryLabel: "Surat Undangan",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Surat undangan resmi",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "surat_permohonan",
    subcategoryLabel: "Surat Permohonan",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Surat permohonan izin/dana",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "surat_tugas",
    subcategoryLabel: "Surat Tugas",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Surat tugas kepanitiaan",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "surat_peminjaman",
    subcategoryLabel: "Surat Peminjaman",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Surat pinjam ruang/alat",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "surat_dispensasi",
    subcategoryLabel: "Surat Dispensasi",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Surat dispensasi kuliah/kerja",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "notulen",
    subcategoryLabel: "Notulen",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "internal",
    notes: "Hasil catatan rapat koordinasi",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "rundown",
    subcategoryLabel: "Rundown",
    outputTypes: ["pdf", "spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Susunan jadwal acara detail",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "tor_term_of_reference",
    subcategoryLabel: "TOR / Term of Reference",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Panduan materi pembicara",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "juknis",
    subcategoryLabel: "Juknis",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Petunjuk teknis lomba/acara",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "buku_panduan",
    subcategoryLabel: "Buku Panduan",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Guidebook panduan event",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "sop",
    subcategoryLabel: "SOP",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Standar operasional prosedur",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "absensi",
    subcategoryLabel: "Absensi",
    outputTypes: ["pdf", "spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "sensitive",
    notes: "Bersifat internal/sensitif",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "daftar_peserta",
    subcategoryLabel: "Daftar Peserta",
    outputTypes: ["pdf", "spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: false,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "sensitive",
    notes: "Data sensitif peserta (tidak untuk referensi)",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "sk_panitia",
    subcategoryLabel: "SK Panitia",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "internal",
    notes: "Struktur kepanitiaan",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "timeline_kerja",
    subcategoryLabel: "Timeline Kerja",
    outputTypes: ["pdf", "spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Jadwal kerja kepanitiaan",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "checklist_perlengkapan",
    subcategoryLabel: "Checklist Perlengkapan",
    outputTypes: ["pdf", "spreadsheet", "checklist"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "List checklist barang divisi",
  },

  // 4. Keuangan dan Spreadsheet
  {
    categoryKey: "keuangan_dan_spreadsheet",
    categoryLabel: "Keuangan dan Spreadsheet",
    subcategoryKey: "rab",
    subcategoryLabel: "RAB",
    outputTypes: ["spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Template anggaran biaya",
  },
  {
    categoryKey: "keuangan_dan_spreadsheet",
    categoryLabel: "Keuangan dan Spreadsheet",
    subcategoryKey: "lpj_keuangan",
    subcategoryLabel: "LPJ Keuangan",
    outputTypes: ["spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Template laporan keuangan",
  },
  {
    categoryKey: "keuangan_dan_spreadsheet",
    categoryLabel: "Keuangan dan Spreadsheet",
    subcategoryKey: "rekap_pengeluaran",
    subcategoryLabel: "Rekap Pengeluaran",
    outputTypes: ["spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "internal",
    notes: "Data keuangan internal",
  },
  {
    categoryKey: "keuangan_dan_spreadsheet",
    categoryLabel: "Keuangan dan Spreadsheet",
    subcategoryKey: "rekap_pemasukan",
    subcategoryLabel: "Rekap Pemasukan",
    outputTypes: ["spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "internal",
    notes: "Data keuangan internal",
  },
  {
    categoryKey: "keuangan_dan_spreadsheet",
    categoryLabel: "Keuangan dan Spreadsheet",
    subcategoryKey: "bukti_pembayaran",
    subcategoryLabel: "Bukti Pembayaran",
    outputTypes: ["image", "pdf"],
    archiveDefault: true,
    referenceDefault: false,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "sensitive",
    notes: "Bukti transfer/kuitansi bayar (sensitif)",
  },
  {
    categoryKey: "keuangan_dan_spreadsheet",
    categoryLabel: "Keuangan dan Spreadsheet",
    subcategoryKey: "invoice",
    subcategoryLabel: "Invoice",
    outputTypes: ["pdf", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Template invoice sponsor/vendor",
  },
  {
    categoryKey: "keuangan_dan_spreadsheet",
    categoryLabel: "Keuangan dan Spreadsheet",
    subcategoryKey: "kwitansi",
    subcategoryLabel: "Kwitansi",
    outputTypes: ["pdf", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Template kuitansi internal",
  },
  {
    categoryKey: "keuangan_dan_spreadsheet",
    categoryLabel: "Keuangan dan Spreadsheet",
    subcategoryKey: "sponsorship_sheet",
    subcategoryLabel: "Sponsorship Sheet",
    outputTypes: ["spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Progres list/database sponsor",
  },
  {
    categoryKey: "keuangan_dan_spreadsheet",
    categoryLabel: "Keuangan dan Spreadsheet",
    subcategoryKey: "konsumsi_sheet",
    subcategoryLabel: "Konsumsi Sheet",
    outputTypes: ["spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "internal",
    notes: "Detail pembagian makanan",
  },
  {
    categoryKey: "keuangan_dan_spreadsheet",
    categoryLabel: "Keuangan dan Spreadsheet",
    subcategoryKey: "transport_sheet",
    subcategoryLabel: "Transport Sheet",
    outputTypes: ["spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "internal",
    notes: "Detail armada/biaya transport",
  },
  {
    categoryKey: "keuangan_dan_spreadsheet",
    categoryLabel: "Keuangan dan Spreadsheet",
    subcategoryKey: "merchandise_sheet",
    subcategoryLabel: "Merchandise Sheet",
    outputTypes: ["spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "internal",
    notes: "Rekap data pemesanan merch",
  },

  // 5. Konten dan Copywriting
  {
    categoryKey: "konten_dan_copywriting",
    categoryLabel: "Konten dan Copywriting",
    subcategoryKey: "caption_instagram",
    subcategoryLabel: "Caption Instagram",
    outputTypes: ["text", "document"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Teks copy sosmed",
  },
  {
    categoryKey: "konten_dan_copywriting",
    categoryLabel: "Konten dan Copywriting",
    subcategoryKey: "copy_poster",
    subcategoryLabel: "Copy Poster",
    outputTypes: ["text", "document"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Teks copy promosi",
  },
  {
    categoryKey: "konten_dan_copywriting",
    categoryLabel: "Konten dan Copywriting",
    subcategoryKey: "press_release",
    subcategoryLabel: "Press Release",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Rilis berita media partner",
  },
  {
    categoryKey: "konten_dan_copywriting",
    categoryLabel: "Konten dan Copywriting",
    subcategoryKey: "narasi_mc",
    subcategoryLabel: "Narasi MC",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Script/pemandu pembacaan MC",
  },
  {
    categoryKey: "konten_dan_copywriting",
    categoryLabel: "Konten dan Copywriting",
    subcategoryKey: "script_voice_over",
    subcategoryLabel: "Script Voice Over",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Naskah rekaman VO",
  },
  {
    categoryKey: "konten_dan_copywriting",
    categoryLabel: "Konten dan Copywriting",
    subcategoryKey: "script_video",
    subcategoryLabel: "Script Video",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Naskah konsep/tata video",
  },
  {
    categoryKey: "konten_dan_copywriting",
    categoryLabel: "Konten dan Copywriting",
    subcategoryKey: "sambutan",
    subcategoryLabel: "Sambutan",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Konsep teks sambutan",
  },
  {
    categoryKey: "konten_dan_copywriting",
    categoryLabel: "Konten dan Copywriting",
    subcategoryKey: "rundown_narasi",
    subcategoryLabel: "Rundown Narasi",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Alur penulisan script detail",
  },
  {
    categoryKey: "konten_dan_copywriting",
    categoryLabel: "Konten dan Copywriting",
    subcategoryKey: "broadcast_message",
    subcategoryLabel: "Broadcast Message",
    outputTypes: ["text", "document"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Pesan broadcast sosmed",
  },
  {
    categoryKey: "konten_dan_copywriting",
    categoryLabel: "Konten dan Copywriting",
    subcategoryKey: "reminder_text",
    subcategoryLabel: "Reminder Text",
    outputTypes: ["text", "document"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Pengingat internal/eksternal",
  },
  {
    categoryKey: "konten_dan_copywriting",
    categoryLabel: "Konten dan Copywriting",
    subcategoryKey: "template_email",
    subcategoryLabel: "Template Email",
    outputTypes: ["text", "document"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Draft template email",
  },

  // 6. Video dan Multimedia
  {
    categoryKey: "video_dan_multimedia",
    categoryLabel: "Video dan Multimedia",
    subcategoryKey: "video_teaser",
    subcategoryLabel: "Video Teaser",
    outputTypes: ["video", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: "optional",
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Penting untuk referensi video promosi",
  },
  {
    categoryKey: "video_dan_multimedia",
    categoryLabel: "Video dan Multimedia",
    subcategoryKey: "video_highlight",
    subcategoryLabel: "Video Highlight",
    outputTypes: ["video", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: "optional",
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Rangkuman visual event",
  },
  {
    categoryKey: "video_dan_multimedia",
    categoryLabel: "Video dan Multimedia",
    subcategoryKey: "video_aftermovie",
    subcategoryLabel: "Video Aftermovie",
    outputTypes: ["video", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: "optional",
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Video aftermovie utama",
  },
  {
    categoryKey: "video_dan_multimedia",
    categoryLabel: "Video dan Multimedia",
    subcategoryKey: "video_dokumentasi",
    subcategoryLabel: "Video Dokumentasi",
    outputTypes: ["video", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: "optional",
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Full video dokumentasi acara",
  },
  {
    categoryKey: "video_dan_multimedia",
    categoryLabel: "Video dan Multimedia",
    subcategoryKey: "video_opening",
    subcategoryLabel: "Video Opening",
    outputTypes: ["video", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: "optional",
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Video pembuka",
  },
  {
    categoryKey: "video_dan_multimedia",
    categoryLabel: "Video dan Multimedia",
    subcategoryKey: "video_bumper",
    subcategoryLabel: "Video Bumper",
    outputTypes: ["video", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: "optional",
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Animasi logo durasi pendek",
  },
  {
    categoryKey: "video_dan_multimedia",
    categoryLabel: "Video dan Multimedia",
    subcategoryKey: "video_testimoni",
    subcategoryLabel: "Video Testimoni",
    outputTypes: ["video", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: "optional",
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Review/tanggapan lisan",
  },
  {
    categoryKey: "video_dan_multimedia",
    categoryLabel: "Video dan Multimedia",
    subcategoryKey: "motion_graphic",
    subcategoryLabel: "Motion Graphic",
    outputTypes: ["video", "drive_link", "figma_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: "optional",
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Animasi grafis promosi",
  },
  {
    categoryKey: "video_dan_multimedia",
    categoryLabel: "Video dan Multimedia",
    subcategoryKey: "lower_third",
    subcategoryLabel: "Lower Third",
    outputTypes: ["video", "image", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Lower third overlay",
  },
  {
    categoryKey: "video_dan_multimedia",
    categoryLabel: "Video dan Multimedia",
    subcategoryKey: "subtitle_file",
    subcategoryLabel: "Subtitle File",
    outputTypes: ["document", "text"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Subtitle srt/vtt",
  },
  {
    categoryKey: "video_dan_multimedia",
    categoryLabel: "Video dan Multimedia",
    subcategoryKey: "audio_backsound",
    subcategoryLabel: "Audio Backsound",
    outputTypes: ["drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "internal",
    notes: "Backsound audio",
  },
  {
    categoryKey: "video_dan_multimedia",
    categoryLabel: "Video dan Multimedia",
    subcategoryKey: "voice_over",
    subcategoryLabel: "Voice Over",
    outputTypes: ["drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Audio narator",
  },

  // 7. Dokumentasi Foto
  {
    categoryKey: "dokumentasi_foto",
    categoryLabel: "Dokumentasi Foto",
    subcategoryKey: "foto_dokumentasi",
    subcategoryLabel: "Foto Dokumentasi",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Foto momen utama",
  },
  {
    categoryKey: "dokumentasi_foto",
    categoryLabel: "Dokumentasi Foto",
    subcategoryKey: "foto_panitia",
    subcategoryLabel: "Foto Panitia",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Foto kepanitiaan divisi/angkatan",
  },
  {
    categoryKey: "dokumentasi_foto",
    categoryLabel: "Dokumentasi Foto",
    subcategoryKey: "foto_peserta",
    subcategoryLabel: "Foto Peserta",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Foto interaksi peserta",
  },
  {
    categoryKey: "dokumentasi_foto",
    categoryLabel: "Dokumentasi Foto",
    subcategoryKey: "foto_narasumber",
    subcategoryLabel: "Foto Narasumber",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Foto pemateri/tamu VIP",
  },
  {
    categoryKey: "dokumentasi_foto",
    categoryLabel: "Dokumentasi Foto",
    subcategoryKey: "foto_venue",
    subcategoryLabel: "Foto Venue",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Dokumentasi dekor/layout venue",
  },
  {
    categoryKey: "dokumentasi_foto",
    categoryLabel: "Dokumentasi Foto",
    subcategoryKey: "foto_produk_barang",
    subcategoryLabel: "Foto Produk/Barang",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Foto barang/booth",
  },
  {
    categoryKey: "dokumentasi_foto",
    categoryLabel: "Dokumentasi Foto",
    subcategoryKey: "foto_behind_the_scene",
    subcategoryLabel: "Foto Behind The Scene",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Dokumentasi persiapan panitia",
  },
  {
    categoryKey: "dokumentasi_foto",
    categoryLabel: "Dokumentasi Foto",
    subcategoryKey: "foto_publikasi",
    subcategoryLabel: "Foto Publikasi",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Foto terpilih pasca editing",
  },
  {
    categoryKey: "dokumentasi_foto",
    categoryLabel: "Dokumentasi Foto",
    subcategoryKey: "selected_photos",
    subcategoryLabel: "Selected Photos",
    outputTypes: ["drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Link folder kurasi foto terbaik",
  },
  {
    categoryKey: "dokumentasi_foto",
    categoryLabel: "Dokumentasi Foto",
    subcategoryKey: "dokumentasi_mentah",
    subcategoryLabel: "Dokumentasi Mentah",
    outputTypes: ["drive_link"],
    archiveDefault: true,
    referenceDefault: false,
    requiresFile: false,
    requiresSourceLink: true,
    sensitivity: "internal",
    notes: "Tautan folder foto RAW kamera",
  },

  // 8. Aset Desain
  {
    categoryKey: "aset_desain",
    categoryLabel: "Aset Desain",
    subcategoryKey: "logo",
    subcategoryLabel: "Logo",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Aset visual logo",
  },
  {
    categoryKey: "aset_desain",
    categoryLabel: "Aset Desain",
    subcategoryKey: "icon",
    subcategoryLabel: "Icon",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Custom icon set",
  },
  {
    categoryKey: "aset_desain",
    categoryLabel: "Aset Desain",
    subcategoryKey: "ilustrasi",
    subcategoryLabel: "Ilustrasi",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Custom illustration",
  },
  {
    categoryKey: "aset_desain",
    categoryLabel: "Aset Desain",
    subcategoryKey: "pattern",
    subcategoryLabel: "Pattern",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Pola background dekoratif",
  },
  {
    categoryKey: "aset_desain",
    categoryLabel: "Aset Desain",
    subcategoryKey: "background",
    subcategoryLabel: "Background",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Latar belakang grafis",
  },
  {
    categoryKey: "aset_desain",
    categoryLabel: "Aset Desain",
    subcategoryKey: "texture",
    subcategoryLabel: "Texture",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Tekstur pendukung visual",
  },
  {
    categoryKey: "aset_desain",
    categoryLabel: "Aset Desain",
    subcategoryKey: "font_pairing",
    subcategoryLabel: "Font Pairing",
    outputTypes: ["text", "image"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Guideline nama-nama font",
  },
  {
    categoryKey: "aset_desain",
    categoryLabel: "Aset Desain",
    subcategoryKey: "color_palette",
    subcategoryLabel: "Color Palette",
    outputTypes: ["image", "text"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Paduan hex warna",
  },
  {
    categoryKey: "aset_desain",
    categoryLabel: "Aset Desain",
    subcategoryKey: "template_canva",
    subcategoryLabel: "Template Canva",
    outputTypes: ["canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Tautan shareable template canva",
  },
  {
    categoryKey: "aset_desain",
    categoryLabel: "Aset Desain",
    subcategoryKey: "template_figma",
    subcategoryLabel: "Template Figma",
    outputTypes: ["figma_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Tautan figma file",
  },
  {
    categoryKey: "aset_desain",
    categoryLabel: "Aset Desain",
    subcategoryKey: "template_photoshop",
    subcategoryLabel: "Template Photoshop",
    outputTypes: ["drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Tautan file PSD di GDrive",
  },
  {
    categoryKey: "aset_desain",
    categoryLabel: "Aset Desain",
    subcategoryKey: "template_illustrator",
    subcategoryLabel: "Template Illustrator",
    outputTypes: ["drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Tautan file AI di GDrive",
  },
  {
    categoryKey: "aset_desain",
    categoryLabel: "Aset Desain",
    subcategoryKey: "mockup",
    subcategoryLabel: "Mockup",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Desain preview visual produk",
  },
  {
    categoryKey: "aset_desain",
    categoryLabel: "Aset Desain",
    subcategoryKey: "asset_drive",
    subcategoryLabel: "Asset Drive",
    outputTypes: ["drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Kumpulan link asset lengkap di Drive",
  },

  // 9. Perlengkapan dan Operasional
  {
    categoryKey: "perlengkapan_dan_operasional",
    categoryLabel: "Perlengkapan dan Operasional",
    subcategoryKey: "list_perlengkapan",
    subcategoryLabel: "List Perlengkapan",
    outputTypes: ["spreadsheet", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Checklist perlengkapan",
  },
  {
    categoryKey: "perlengkapan_dan_operasional",
    categoryLabel: "Perlengkapan dan Operasional",
    subcategoryKey: "inventaris_acara",
    subcategoryLabel: "Inventaris Acara",
    outputTypes: ["spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Catatan log barang inventaris",
  },
  {
    categoryKey: "perlengkapan_dan_operasional",
    categoryLabel: "Perlengkapan dan Operasional",
    subcategoryKey: "peminjaman_alat",
    subcategoryLabel: "Peminjaman Alat",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Surat pinjam alat",
  },
  {
    categoryKey: "perlengkapan_dan_operasional",
    categoryLabel: "Perlengkapan dan Operasional",
    subcategoryKey: "layout_ruangan",
    subcategoryLabel: "Layout Ruangan",
    outputTypes: ["image", "pdf", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Denah tata letak panggung/meja",
  },
  {
    categoryKey: "perlengkapan_dan_operasional",
    categoryLabel: "Perlengkapan dan Operasional",
    subcategoryKey: "denah_venue",
    subcategoryLabel: "Denah Venue",
    outputTypes: ["image", "pdf"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Peta lokasi ruangan/tempat",
  },
  {
    categoryKey: "perlengkapan_dan_operasional",
    categoryLabel: "Perlengkapan dan Operasional",
    subcategoryKey: "rundown_teknis",
    subcategoryLabel: "Rundown Teknis",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Rundown detail divisi acara & perlengkapan",
  },
  {
    categoryKey: "perlengkapan_dan_operasional",
    categoryLabel: "Perlengkapan dan Operasional",
    subcategoryKey: "cue_card",
    subcategoryLabel: "Cue Card",
    outputTypes: ["pdf", "document", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Kartu pemandu MC/operator",
  },
  {
    categoryKey: "perlengkapan_dan_operasional",
    categoryLabel: "Perlengkapan dan Operasional",
    subcategoryKey: "operator_notes",
    subcategoryLabel: "Operator Notes",
    outputTypes: ["pdf", "document", "text"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Catatan operator sound/slide",
  },
  {
    categoryKey: "perlengkapan_dan_operasional",
    categoryLabel: "Perlengkapan dan Operasional",
    subcategoryKey: "lighting_notes",
    subcategoryLabel: "Lighting Notes",
    outputTypes: ["pdf", "document", "text"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Catatan tata lampu",
  },
  {
    categoryKey: "perlengkapan_dan_operasional",
    categoryLabel: "Perlengkapan dan Operasional",
    subcategoryKey: "sound_notes",
    subcategoryLabel: "Sound Notes",
    outputTypes: ["pdf", "document", "text"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Catatan soundcheck",
  },

  // 10. Koordinasi dan Aktivitas Non-File
  {
    categoryKey: "koordinasi_dan_aktivitas_non_file",
    categoryLabel: "Koordinasi dan Aktivitas Non-File",
    subcategoryKey: "briefing",
    subcategoryLabel: "Briefing",
    outputTypes: ["activity_log", "text"],
    archiveDefault: "optional",
    referenceDefault: false,
    requiresFile: false,
    requiresSourceLink: false,
    sensitivity: "internal",
    notes: "Catatan koordinasi internal",
  },
  {
    categoryKey: "koordinasi_dan_aktivitas_non_file",
    categoryLabel: "Koordinasi dan Aktivitas Non-File",
    subcategoryKey: "koordinasi_sie_lain",
    subcategoryLabel: "Koordinasi Sie Lain",
    outputTypes: ["activity_log", "text"],
    archiveDefault: "optional",
    referenceDefault: false,
    requiresFile: false,
    requiresSourceLink: false,
    sensitivity: "internal",
    notes: "Catatan koordinasi lintas divisi",
  },
  {
    categoryKey: "koordinasi_dan_aktivitas_non_file",
    categoryLabel: "Koordinasi dan Aktivitas Non-File",
    subcategoryKey: "follow_up_pic",
    subcategoryLabel: "Follow-up PIC",
    outputTypes: ["activity_log", "text"],
    archiveDefault: "optional",
    referenceDefault: false,
    requiresFile: false,
    requiresSourceLink: false,
    sensitivity: "internal",
    notes: "Pantau progres tugas tim",
  },
  {
    categoryKey: "koordinasi_dan_aktivitas_non_file",
    categoryLabel: "Koordinasi dan Aktivitas Non-File",
    subcategoryKey: "rapat_internal",
    subcategoryLabel: "Rapat Internal",
    outputTypes: ["activity_log", "text"],
    archiveDefault: "optional",
    referenceDefault: false,
    requiresFile: false,
    requiresSourceLink: false,
    sensitivity: "internal",
    notes: "Catatan notula rapat internal",
  },
  {
    categoryKey: "koordinasi_dan_aktivitas_non_file",
    categoryLabel: "Koordinasi dan Aktivitas Non-File",
    subcategoryKey: "distribusi_tugas",
    subcategoryLabel: "Distribusi Tugas",
    outputTypes: ["activity_log", "text", "checklist"],
    archiveDefault: "optional",
    referenceDefault: false,
    requiresFile: false,
    requiresSourceLink: false,
    sensitivity: "internal",
    notes: "Plot penugasan",
  },
  {
    categoryKey: "koordinasi_dan_aktivitas_non_file",
    categoryLabel: "Koordinasi dan Aktivitas Non-File",
    subcategoryKey: "cek_kesiapan",
    subcategoryLabel: "Cek Kesiapan",
    outputTypes: ["activity_log", "text", "checklist"],
    archiveDefault: "optional",
    referenceDefault: false,
    requiresFile: false,
    requiresSourceLink: false,
    sensitivity: "internal",
    notes: "Pengecekan item",
  },
  {
    categoryKey: "koordinasi_dan_aktivitas_non_file",
    categoryLabel: "Koordinasi dan Aktivitas Non-File",
    subcategoryKey: "konfirmasi_vendor",
    subcategoryLabel: "Konfirmasi Vendor",
    outputTypes: ["activity_log", "text"],
    archiveDefault: "optional",
    referenceDefault: false,
    requiresFile: false,
    requiresSourceLink: false,
    sensitivity: "internal",
    notes: "Catatan konfirmasi vendor",
  },
  {
    categoryKey: "koordinasi_dan_aktivitas_non_file",
    categoryLabel: "Koordinasi dan Aktivitas Non-File",
    subcategoryKey: "konfirmasi_narasumber",
    subcategoryLabel: "Konfirmasi Narasumber",
    outputTypes: ["activity_log", "text"],
    archiveDefault: "optional",
    referenceDefault: false,
    requiresFile: false,
    requiresSourceLink: false,
    sensitivity: "internal",
    notes: "Catatan konfirmasi narasumber",
  },
  {
    categoryKey: "koordinasi_dan_aktivitas_non_file",
    categoryLabel: "Koordinasi dan Aktivitas Non-File",
    subcategoryKey: "reminder_internal",
    subcategoryLabel: "Reminder Internal",
    outputTypes: ["activity_log", "text"],
    archiveDefault: "optional",
    referenceDefault: false,
    requiresFile: false,
    requiresSourceLink: false,
    sensitivity: "internal",
    notes: "Reminder deadline",
  },
  {
    categoryKey: "koordinasi_dan_aktivitas_non_file",
    categoryLabel: "Koordinasi dan Aktivitas Non-File",
    subcategoryKey: "monitoring_progress",
    subcategoryLabel: "Monitoring Progress",
    outputTypes: ["activity_log", "text"],
    archiveDefault: "optional",
    referenceDefault: false,
    requiresFile: false,
    requiresSourceLink: false,
    sensitivity: "internal",
    notes: "Catatan pantauan progress",
  },
  {
    categoryKey: "koordinasi_dan_aktivitas_non_file",
    categoryLabel: "Koordinasi dan Aktivitas Non-File",
    subcategoryKey: "review_internal",
    subcategoryLabel: "Review Internal",
    outputTypes: ["activity_log", "text"],
    archiveDefault: "optional",
    referenceDefault: false,
    requiresFile: false,
    requiresSourceLink: false,
    sensitivity: "internal",
    notes: "Review pengerjaan",
  },
  {
    categoryKey: "koordinasi_dan_aktivitas_non_file",
    categoryLabel: "Koordinasi dan Aktivitas Non-File",
    subcategoryKey: "quality_control",
    subcategoryLabel: "Quality Control",
    outputTypes: ["activity_log", "text"],
    archiveDefault: "optional",
    referenceDefault: false,
    requiresFile: false,
    requiresSourceLink: false,
    sensitivity: "internal",
    notes: "QC kelayakan output",
  },

  // 11. Publikasi dan Media Sosial
  {
    categoryKey: "publikasi_dan_media_sosial",
    categoryLabel: "Publikasi dan Media Sosial",
    subcategoryKey: "jadwal_posting",
    subcategoryLabel: "Jadwal Posting",
    outputTypes: ["spreadsheet", "image", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Rencana upload konten",
  },
  {
    categoryKey: "publikasi_dan_media_sosial",
    categoryLabel: "Publikasi dan Media Sosial",
    subcategoryKey: "content_plan",
    subcategoryLabel: "Content Plan",
    outputTypes: ["spreadsheet", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Konsep tulisan/visual konten",
  },
  {
    categoryKey: "publikasi_dan_media_sosial",
    categoryLabel: "Publikasi dan Media Sosial",
    subcategoryKey: "content_calendar",
    subcategoryLabel: "Content Calendar",
    outputTypes: ["spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Jadwal bulanan konten",
  },
  {
    categoryKey: "publikasi_dan_media_sosial",
    categoryLabel: "Publikasi dan Media Sosial",
    subcategoryKey: "draft_feed",
    subcategoryLabel: "Draft Feed",
    outputTypes: ["image", "canva_link", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Draft postingan feed",
  },
  {
    categoryKey: "publikasi_dan_media_sosial",
    categoryLabel: "Publikasi dan Media Sosial",
    subcategoryKey: "draft_story",
    subcategoryLabel: "Draft Story",
    outputTypes: ["image", "canva_link", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Draft postingan story",
  },
  {
    categoryKey: "publikasi_dan_media_sosial",
    categoryLabel: "Publikasi dan Media Sosial",
    subcategoryKey: "draft_reels",
    subcategoryLabel: "Draft Reels",
    outputTypes: ["video", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Draft postingan video pendek",
  },
  {
    categoryKey: "publikasi_dan_media_sosial",
    categoryLabel: "Publikasi dan Media Sosial",
    subcategoryKey: "caption_plan",
    subcategoryLabel: "Caption Plan",
    outputTypes: ["text", "document"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Teks caption postingan",
  },
  {
    categoryKey: "publikasi_dan_media_sosial",
    categoryLabel: "Publikasi dan Media Sosial",
    subcategoryKey: "hashtag_list",
    subcategoryLabel: "Hashtag List",
    outputTypes: ["text", "document"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Daftar hashtag relevan",
  },
  {
    categoryKey: "publikasi_dan_media_sosial",
    categoryLabel: "Publikasi dan Media Sosial",
    subcategoryKey: "media_partner_kit",
    subcategoryLabel: "Media Partner Kit",
    outputTypes: ["pdf", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Proposal/materi medpart",
  },
  {
    categoryKey: "publikasi_dan_media_sosial",
    categoryLabel: "Publikasi dan Media Sosial",
    subcategoryKey: "publikasi_final",
    subcategoryLabel: "Publikasi Final",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Tangkapan layar bukti postingan tayang",
  },
  {
    categoryKey: "publikasi_dan_media_sosial",
    categoryLabel: "Publikasi dan Media Sosial",
    subcategoryKey: "insight_report",
    subcategoryLabel: "Insight Report",
    outputTypes: ["pdf", "image", "spreadsheet"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Laporan performa pasca event",
  },

  // 12. Registrasi dan Peserta
  {
    categoryKey: "registrasi_dan_peserta",
    categoryLabel: "Registrasi dan Peserta",
    subcategoryKey: "form_pendaftaran",
    subcategoryLabel: "Form Pendaftaran",
    outputTypes: ["drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Link form registrasi online",
  },
  {
    categoryKey: "registrasi_dan_peserta",
    categoryLabel: "Registrasi dan Peserta",
    subcategoryKey: "header_google_form",
    subcategoryLabel: "Header Google Form",
    outputTypes: ["image", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Banner header form",
  },
  {
    categoryKey: "registrasi_dan_peserta",
    categoryLabel: "Registrasi dan Peserta",
    subcategoryKey: "rekap_pendaftar",
    subcategoryLabel: "Rekap Pendaftar",
    outputTypes: ["spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: false,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "sensitive",
    notes: "Rekap pendaftar (sensitif)",
  },
  {
    categoryKey: "registrasi_dan_peserta",
    categoryLabel: "Registrasi dan Peserta",
    subcategoryKey: "rekap_kehadiran",
    subcategoryLabel: "Rekap Kehadiran",
    outputTypes: ["spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: false,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "sensitive",
    notes: "Absensi kehadiran (sensitif)",
  },
  {
    categoryKey: "registrasi_dan_peserta",
    categoryLabel: "Registrasi dan Peserta",
    subcategoryKey: "sertifikat_peserta",
    subcategoryLabel: "Sertifikat Peserta",
    outputTypes: ["drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Drive folder sertifikat massal",
  },
  {
    categoryKey: "registrasi_dan_peserta",
    categoryLabel: "Registrasi dan Peserta",
    subcategoryKey: "e_ticket",
    subcategoryLabel: "E-ticket",
    outputTypes: ["pdf", "image", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Tiket masuk elektronik",
  },
  {
    categoryKey: "registrasi_dan_peserta",
    categoryLabel: "Registrasi dan Peserta",
    subcategoryKey: "kupon",
    subcategoryLabel: "Kupon",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Kupon bazar/konsumsi",
  },
  {
    categoryKey: "registrasi_dan_peserta",
    categoryLabel: "Registrasi dan Peserta",
    subcategoryKey: "qr_code_peserta",
    subcategoryLabel: "QR Code Peserta",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "QR check-in peserta",
  },
  {
    categoryKey: "registrasi_dan_peserta",
    categoryLabel: "Registrasi dan Peserta",
    subcategoryKey: "data_delegasi",
    subcategoryLabel: "Data Delegasi",
    outputTypes: ["spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: false,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "sensitive",
    notes: "Data detail delegasi (sensitif)",
  },
];

export function getMainCategories() {
  return MAIN_CATEGORIES;
}

export function getSubcategories(categoryKey: string) {
  return CATEGORY_RULES.filter((rule) => rule.categoryKey === categoryKey).map((rule) => ({
    key: rule.subcategoryKey,
    label: rule.subcategoryLabel,
  }));
}

export function getCategoryRule(categoryKey: string, subcategoryKey: string): JobdeskCategoryRule | null {
  return CATEGORY_RULES.find((rule) => rule.categoryKey === categoryKey && rule.subcategoryKey === subcategoryKey) || null;
}

export function getDefaultArchiveSettings(categoryKey: string, subcategoryKey: string) {
  const rule = getCategoryRule(categoryKey, subcategoryKey);
  if (!rule) {
    return {
      archiveEnabled: true,
      referenceCandidateEnabled: false,
      requiresFile: false,
      requiresSourceLink: false,
      outputTypes: [] as string[],
      dataSensitivity: "normal" as const,
    };
  }
  return {
    archiveEnabled: rule.archiveDefault === true || rule.archiveDefault === "optional",
    referenceCandidateEnabled: rule.referenceDefault === true,
    requiresFile: rule.requiresFile === true,
    requiresSourceLink: rule.requiresSourceLink === true,
    outputTypes: rule.outputTypes,
    dataSensitivity: rule.sensitivity,
  };
}
