export type ArchiveDefault = true | false | "optional";
export type ReferenceDefault = true | false | "optional";

export type JobdeskCategoryRule = {
  categoryKey: string;
  categoryLabel: string;
  subcategoryKey: string;
  subcategoryLabel: string;
  outputTypes: string[];
  archiveDefault: ArchiveDefault;
  referenceDefault: ReferenceDefault;
  requiresFile: boolean | "optional";
  requiresSourceLink: boolean | "optional";
  sensitivity: "normal" | "internal" | "sensitive";
  notes?: string;
};

export const MAIN_CATEGORIES = [
  { key: "desain_publikasi", label: "Desain Publikasi" },
  { key: "identitas_acara_dan_panitia", label: "Identitas Acara dan Panitia" },
  { key: "dokumen_administrasi", label: "Dokumen Administrasi" },
  { key: "keuangan_dan_spreadsheet", label: "Keuangan dan Spreadsheet" },
  { key: "konten_dan_copywriting", label: "Konten dan Copywriting" },
  { key: "video_dan_multimedia", label: "Video dan Multimedia" },
  { key: "dokumentasi_foto", label: "Dokumentasi Foto" },
  { key: "aset_desain", label: "Aset Desain" },
  { key: "perlengkapan_dan_operasional", label: "Perlengkapan dan Operasional" },
  { key: "koordinasi_dan_aktivitas_non_file", label: "Koordinasi dan Aktivitas Non-File" },
  { key: "publikasi_dan_media_sosial", label: "Publikasi dan Media Sosial" },
  { key: "registrasi_dan_peserta", label: "Registrasi dan Peserta" },
];

export const CATEGORY_RULES: JobdeskCategoryRule[] = [
  // 1. Desain Publikasi
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "poster",
    subcategoryLabel: "Poster",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Cocok untuk referensi desain",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "pamflet",
    subcategoryLabel: "Pamflet",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Cocok untuk referensi desain",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "flyer",
    subcategoryLabel: "Flyer",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Cocok untuk referensi desain",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "feed_instagram",
    subcategoryLabel: "Feed Instagram",
    outputTypes: ["image", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Desain feed media sosial",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "story_instagram",
    subcategoryLabel: "Story Instagram",
    outputTypes: ["image", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Berguna untuk referensi template story",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "reels_cover",
    subcategoryLabel: "Reels Cover",
    outputTypes: ["image", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Desain cover video pendek",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "thumbnail_video",
    subcategoryLabel: "Thumbnail Video",
    outputTypes: ["image", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Desain cover YouTube/highlight",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "banner_digital",
    subcategoryLabel: "Banner Digital",
    outputTypes: ["image", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Desain banner landscape digital",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "spanduk_banner_cetak",
    subcategoryLabel: "Spanduk / Banner Cetak",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Desain spanduk fisik",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "x_banner",
    subcategoryLabel: "X-Banner",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Desain standing banner cetak",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "baliho",
    subcategoryLabel: "Baliho",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Desain cetak baliho besar",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "twibbon",
    subcategoryLabel: "Twibbon",
    outputTypes: ["image", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Biasanya format PNG transparan",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "frame_foto",
    subcategoryLabel: "Frame Foto",
    outputTypes: ["image", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Overlay frame dokumentasi",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "photobooth",
    subcategoryLabel: "Photobooth",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Layout desain photobooth fisik",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "background_zoom",
    subcategoryLabel: "Background Zoom",
    outputTypes: ["image", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Resolusi landscape 16:9",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "countdown_design",
    subcategoryLabel: "Countdown Design",
    outputTypes: ["image", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Desain hitung mundur event",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "announcement_design",
    subcategoryLabel: "Announcement Design",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Desain pengumuman hasil",
  },
  {
    categoryKey: "desain_publikasi",
    categoryLabel: "Desain Publikasi",
    subcategoryKey: "thank_you_post",
    subcategoryLabel: "Thank You Post",
    outputTypes: ["image", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Desain ucapan penutup acara",
  },

  // 2. Identitas Acara dan Panitia
  {
    categoryKey: "identitas_acara_dan_panitia",
    categoryLabel: "Identitas Acara dan Panitia",
    subcategoryKey: "name_tag",
    subcategoryLabel: "Name Tag",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Identitas peserta/panitia",
  },
  {
    categoryKey: "identitas_acara_dan_panitia",
    categoryLabel: "Identitas Acara dan Panitia",
    subcategoryKey: "id_card",
    subcategoryLabel: "ID Card",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Kartu panitia/crew",
  },
  {
    categoryKey: "identitas_acara_dan_panitia",
    categoryLabel: "Identitas Acara dan Panitia",
    subcategoryKey: "kartu_panitia",
    subcategoryLabel: "Kartu Panitia",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Versi lokal name tag",
  },
  {
    categoryKey: "identitas_acara_dan_panitia",
    categoryLabel: "Identitas Acara dan Panitia",
    subcategoryKey: "badge_peserta",
    subcategoryLabel: "Badge Peserta",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Identitas delegasi/peserta",
  },
  {
    categoryKey: "identitas_acara_dan_panitia",
    categoryLabel: "Identitas Acara dan Panitia",
    subcategoryKey: "sertifikat",
    subcategoryLabel: "Sertifikat",
    outputTypes: ["image", "pdf", "canva_link", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: "optional",
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Template sertifikat sangat penting",
  },
  {
    categoryKey: "identitas_acara_dan_panitia",
    categoryLabel: "Identitas Acara dan Panitia",
    subcategoryKey: "piagam",
    subcategoryLabel: "Piagam",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Desain piagam pemenang/mitra",
  },
  {
    categoryKey: "identitas_acara_dan_panitia",
    categoryLabel: "Identitas Acara dan Panitia",
    subcategoryKey: "plakat_design",
    subcategoryLabel: "Plakat Design",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Desain plakat/cenderamata",
  },
  {
    categoryKey: "identitas_acara_dan_panitia",
    categoryLabel: "Identitas Acara dan Panitia",
    subcategoryKey: "kop_surat_acara",
    subcategoryLabel: "Kop Surat Acara",
    outputTypes: ["image", "document", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Kop surat resmi kepanitiaan",
  },
  {
    categoryKey: "identitas_acara_dan_panitia",
    categoryLabel: "Identitas Acara dan Panitia",
    subcategoryKey: "logo_acara",
    subcategoryLabel: "Logo Acara",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Logo utama event",
  },
  {
    categoryKey: "identitas_acara_dan_panitia",
    categoryLabel: "Identitas Acara dan Panitia",
    subcategoryKey: "maskot_acara",
    subcategoryLabel: "Maskot Acara",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Maskot/karakter event",
  },
  {
    categoryKey: "identitas_acara_dan_panitia",
    categoryLabel: "Identitas Acara dan Panitia",
    subcategoryKey: "brand_guideline_acara",
    subcategoryLabel: "Brand Guideline Acara",
    outputTypes: ["pdf", "canva_link", "figma_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Panduan identitas visual",
  },
  {
    categoryKey: "identitas_acara_dan_panitia",
    categoryLabel: "Identitas Acara dan Panitia",
    subcategoryKey: "color_palette",
    subcategoryLabel: "Color Palette",
    outputTypes: ["image", "canva_link", "figma_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Kode warna branding",
  },
  {
    categoryKey: "identitas_acara_dan_panitia",
    categoryLabel: "Identitas Acara dan Panitia",
    subcategoryKey: "supergraphic",
    subcategoryLabel: "Supergraphic",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Elemen grafis dekoratif",
  },

  // 3. Dokumen Administrasi
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "proposal",
    subcategoryLabel: "Proposal",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Template proposal kegiatan",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "cover_proposal",
    subcategoryLabel: "Cover Proposal",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Desain cover depan proposal",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "lpj",
    subcategoryLabel: "LPJ",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Template laporan pertanggungjawaban",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "surat_undangan",
    subcategoryLabel: "Surat Undangan",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Surat undangan resmi",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "surat_permohonan",
    subcategoryLabel: "Surat Permohonan",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Surat permohonan izin/dana",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "surat_tugas",
    subcategoryLabel: "Surat Tugas",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Surat tugas kepanitiaan",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "surat_peminjaman",
    subcategoryLabel: "Surat Peminjaman",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Surat pinjam ruang/alat",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "surat_dispensasi",
    subcategoryLabel: "Surat Dispensasi",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Surat dispensasi kuliah/kerja",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "notulen",
    subcategoryLabel: "Notulen",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "internal",
    notes: "Hasil catatan rapat koordinasi",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "rundown",
    subcategoryLabel: "Rundown",
    outputTypes: ["pdf", "spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Susunan jadwal acara detail",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "tor_term_of_reference",
    subcategoryLabel: "TOR / Term of Reference",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Panduan materi pembicara",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "juknis",
    subcategoryLabel: "Juknis",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Petunjuk teknis lomba/acara",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "buku_panduan",
    subcategoryLabel: "Buku Panduan",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Guidebook panduan event",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "sop",
    subcategoryLabel: "SOP",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Standar operasional prosedur",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "absensi",
    subcategoryLabel: "Absensi",
    outputTypes: ["pdf", "spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "sensitive",
    notes: "Bersifat internal/sensitif",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "daftar_peserta",
    subcategoryLabel: "Daftar Peserta",
    outputTypes: ["pdf", "spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: false,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "sensitive",
    notes: "Data sensitif peserta (tidak untuk referensi)",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "sk_panitia",
    subcategoryLabel: "SK Panitia",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "internal",
    notes: "Struktur kepanitiaan",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "timeline_kerja",
    subcategoryLabel: "Timeline Kerja",
    outputTypes: ["pdf", "spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Jadwal kerja kepanitiaan",
  },
  {
    categoryKey: "dokumen_administrasi",
    categoryLabel: "Dokumen Administrasi",
    subcategoryKey: "checklist_perlengkapan",
    subcategoryLabel: "Checklist Perlengkapan",
    outputTypes: ["pdf", "spreadsheet", "checklist"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "List checklist barang divisi",
  },

  // 4. Keuangan dan Spreadsheet
  {
    categoryKey: "keuangan_dan_spreadsheet",
    categoryLabel: "Keuangan dan Spreadsheet",
    subcategoryKey: "rab",
    subcategoryLabel: "RAB",
    outputTypes: ["spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Template anggaran biaya",
  },
  {
    categoryKey: "keuangan_dan_spreadsheet",
    categoryLabel: "Keuangan dan Spreadsheet",
    subcategoryKey: "lpj_keuangan",
    subcategoryLabel: "LPJ Keuangan",
    outputTypes: ["spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Template laporan keuangan",
  },
  {
    categoryKey: "keuangan_dan_spreadsheet",
    categoryLabel: "Keuangan dan Spreadsheet",
    subcategoryKey: "rekap_pengeluaran",
    subcategoryLabel: "Rekap Pengeluaran",
    outputTypes: ["spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "internal",
    notes: "Data keuangan internal",
  },
  {
    categoryKey: "keuangan_dan_spreadsheet",
    categoryLabel: "Keuangan dan Spreadsheet",
    subcategoryKey: "rekap_pemasukan",
    subcategoryLabel: "Rekap Pemasukan",
    outputTypes: ["spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "internal",
    notes: "Data keuangan internal",
  },
  {
    categoryKey: "keuangan_dan_spreadsheet",
    categoryLabel: "Keuangan dan Spreadsheet",
    subcategoryKey: "bukti_pembayaran",
    subcategoryLabel: "Bukti Pembayaran",
    outputTypes: ["image", "pdf"],
    archiveDefault: true,
    referenceDefault: false,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "sensitive",
    notes: "Bukti transfer/kuitansi bayar (sensitif)",
  },
  {
    categoryKey: "keuangan_dan_spreadsheet",
    categoryLabel: "Keuangan dan Spreadsheet",
    subcategoryKey: "invoice",
    subcategoryLabel: "Invoice",
    outputTypes: ["pdf", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Template invoice sponsor/vendor",
  },
  {
    categoryKey: "keuangan_dan_spreadsheet",
    categoryLabel: "Keuangan dan Spreadsheet",
    subcategoryKey: "kwitansi",
    subcategoryLabel: "Kwitansi",
    outputTypes: ["pdf", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Template kuitansi internal",
  },
  {
    categoryKey: "keuangan_dan_spreadsheet",
    categoryLabel: "Keuangan dan Spreadsheet",
    subcategoryKey: "sponsorship_sheet",
    subcategoryLabel: "Sponsorship Sheet",
    outputTypes: ["spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Progres list/database sponsor",
  },
  {
    categoryKey: "keuangan_dan_spreadsheet",
    categoryLabel: "Keuangan dan Spreadsheet",
    subcategoryKey: "konsumsi_sheet",
    subcategoryLabel: "Konsumsi Sheet",
    outputTypes: ["spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "internal",
    notes: "Detail pembagian makanan",
  },
  {
    categoryKey: "keuangan_dan_spreadsheet",
    categoryLabel: "Keuangan dan Spreadsheet",
    subcategoryKey: "transport_sheet",
    subcategoryLabel: "Transport Sheet",
    outputTypes: ["spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "internal",
    notes: "Detail armada/biaya transport",
  },
  {
    categoryKey: "keuangan_dan_spreadsheet",
    categoryLabel: "Keuangan dan Spreadsheet",
    subcategoryKey: "merchandise_sheet",
    subcategoryLabel: "Merchandise Sheet",
    outputTypes: ["spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "internal",
    notes: "Rekap data pemesanan merch",
  },

  // 5. Konten dan Copywriting
  {
    categoryKey: "konten_dan_copywriting",
    categoryLabel: "Konten dan Copywriting",
    subcategoryKey: "caption_instagram",
    subcategoryLabel: "Caption Instagram",
    outputTypes: ["text", "document"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Teks copy sosmed",
  },
  {
    categoryKey: "konten_dan_copywriting",
    categoryLabel: "Konten dan Copywriting",
    subcategoryKey: "copy_poster",
    subcategoryLabel: "Copy Poster",
    outputTypes: ["text", "document"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Teks copy promosi",
  },
  {
    categoryKey: "konten_dan_copywriting",
    categoryLabel: "Konten dan Copywriting",
    subcategoryKey: "press_release",
    subcategoryLabel: "Press Release",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Rilis berita media partner",
  },
  {
    categoryKey: "konten_dan_copywriting",
    categoryLabel: "Konten dan Copywriting",
    subcategoryKey: "narasi_mc",
    subcategoryLabel: "Narasi MC",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Script/pemandu pembacaan MC",
  },
  {
    categoryKey: "konten_dan_copywriting",
    categoryLabel: "Konten dan Copywriting",
    subcategoryKey: "script_voice_over",
    subcategoryLabel: "Script Voice Over",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Naskah rekaman VO",
  },
  {
    categoryKey: "konten_dan_copywriting",
    categoryLabel: "Konten dan Copywriting",
    subcategoryKey: "script_video",
    subcategoryLabel: "Script Video",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Naskah konsep/tata video",
  },
  {
    categoryKey: "konten_dan_copywriting",
    categoryLabel: "Konten dan Copywriting",
    subcategoryKey: "sambutan",
    subcategoryLabel: "Sambutan",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Konsep teks sambutan",
  },
  {
    categoryKey: "konten_dan_copywriting",
    categoryLabel: "Konten dan Copywriting",
    subcategoryKey: "rundown_narasi",
    subcategoryLabel: "Rundown Narasi",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Alur penulisan script detail",
  },
  {
    categoryKey: "konten_dan_copywriting",
    categoryLabel: "Konten dan Copywriting",
    subcategoryKey: "broadcast_message",
    subcategoryLabel: "Broadcast Message",
    outputTypes: ["text", "document"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Pesan broadcast sosmed",
  },
  {
    categoryKey: "konten_dan_copywriting",
    categoryLabel: "Konten dan Copywriting",
    subcategoryKey: "reminder_text",
    subcategoryLabel: "Reminder Text",
    outputTypes: ["text", "document"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Pengingat internal/eksternal",
  },
  {
    categoryKey: "konten_dan_copywriting",
    categoryLabel: "Konten dan Copywriting",
    subcategoryKey: "template_email",
    subcategoryLabel: "Template Email",
    outputTypes: ["text", "document"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Draft template email",
  },

  // 6. Video dan Multimedia
  {
    categoryKey: "video_dan_multimedia",
    categoryLabel: "Video dan Multimedia",
    subcategoryKey: "video_teaser",
    subcategoryLabel: "Video Teaser",
    outputTypes: ["video", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: "optional",
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Penting untuk referensi video promosi",
  },
  {
    categoryKey: "video_dan_multimedia",
    categoryLabel: "Video dan Multimedia",
    subcategoryKey: "video_highlight",
    subcategoryLabel: "Video Highlight",
    outputTypes: ["video", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: "optional",
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Rangkuman visual event",
  },
  {
    categoryKey: "video_dan_multimedia",
    categoryLabel: "Video dan Multimedia",
    subcategoryKey: "video_aftermovie",
    subcategoryLabel: "Video Aftermovie",
    outputTypes: ["video", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: "optional",
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Video aftermovie utama",
  },
  {
    categoryKey: "video_dan_multimedia",
    categoryLabel: "Video dan Multimedia",
    subcategoryKey: "video_dokumentasi",
    subcategoryLabel: "Video Dokumentasi",
    outputTypes: ["video", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: "optional",
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Full video dokumentasi acara",
  },
  {
    categoryKey: "video_dan_multimedia",
    categoryLabel: "Video dan Multimedia",
    subcategoryKey: "video_opening",
    subcategoryLabel: "Video Opening",
    outputTypes: ["video", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: "optional",
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Video pembuka",
  },
  {
    categoryKey: "video_dan_multimedia",
    categoryLabel: "Video dan Multimedia",
    subcategoryKey: "video_bumper",
    subcategoryLabel: "Video Bumper",
    outputTypes: ["video", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: "optional",
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Animasi logo durasi pendek",
  },
  {
    categoryKey: "video_dan_multimedia",
    categoryLabel: "Video dan Multimedia",
    subcategoryKey: "video_testimoni",
    subcategoryLabel: "Video Testimoni",
    outputTypes: ["video", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: "optional",
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Review/tanggapan lisan",
  },
  {
    categoryKey: "video_dan_multimedia",
    categoryLabel: "Video dan Multimedia",
    subcategoryKey: "motion_graphic",
    subcategoryLabel: "Motion Graphic",
    outputTypes: ["video", "drive_link", "figma_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: "optional",
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Animasi grafis promosi",
  },
  {
    categoryKey: "video_dan_multimedia",
    categoryLabel: "Video dan Multimedia",
    subcategoryKey: "lower_third",
    subcategoryLabel: "Lower Third",
    outputTypes: ["video", "image", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Lower third overlay",
  },
  {
    categoryKey: "video_dan_multimedia",
    categoryLabel: "Video dan Multimedia",
    subcategoryKey: "subtitle_file",
    subcategoryLabel: "Subtitle File",
    outputTypes: ["document", "text"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Subtitle srt/vtt",
  },
  {
    categoryKey: "video_dan_multimedia",
    categoryLabel: "Video dan Multimedia",
    subcategoryKey: "audio_backsound",
    subcategoryLabel: "Audio Backsound",
    outputTypes: ["drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "internal",
    notes: "Backsound audio",
  },
  {
    categoryKey: "video_dan_multimedia",
    categoryLabel: "Video dan Multimedia",
    subcategoryKey: "voice_over",
    subcategoryLabel: "Voice Over",
    outputTypes: ["drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Audio narator",
  },

  // 7. Dokumentasi Foto
  {
    categoryKey: "dokumentasi_foto",
    categoryLabel: "Dokumentasi Foto",
    subcategoryKey: "foto_dokumentasi",
    subcategoryLabel: "Foto Dokumentasi",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Foto momen utama",
  },
  {
    categoryKey: "dokumentasi_foto",
    categoryLabel: "Dokumentasi Foto",
    subcategoryKey: "foto_panitia",
    subcategoryLabel: "Foto Panitia",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Foto kepanitiaan divisi/angkatan",
  },
  {
    categoryKey: "dokumentasi_foto",
    categoryLabel: "Dokumentasi Foto",
    subcategoryKey: "foto_peserta",
    subcategoryLabel: "Foto Peserta",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Foto interaksi peserta",
  },
  {
    categoryKey: "dokumentasi_foto",
    categoryLabel: "Dokumentasi Foto",
    subcategoryKey: "foto_narasumber",
    subcategoryLabel: "Foto Narasumber",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Foto pemateri/tamu VIP",
  },
  {
    categoryKey: "dokumentasi_foto",
    categoryLabel: "Dokumentasi Foto",
    subcategoryKey: "foto_venue",
    subcategoryLabel: "Foto Venue",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Dokumentasi dekor/layout venue",
  },
  {
    categoryKey: "dokumentasi_foto",
    categoryLabel: "Dokumentasi Foto",
    subcategoryKey: "foto_produk_barang",
    subcategoryLabel: "Foto Produk/Barang",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Foto barang/booth",
  },
  {
    categoryKey: "dokumentasi_foto",
    categoryLabel: "Dokumentasi Foto",
    subcategoryKey: "foto_behind_the_scene",
    subcategoryLabel: "Foto Behind The Scene",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Dokumentasi persiapan panitia",
  },
  {
    categoryKey: "dokumentasi_foto",
    categoryLabel: "Dokumentasi Foto",
    subcategoryKey: "foto_publikasi",
    subcategoryLabel: "Foto Publikasi",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Foto terpilih pasca editing",
  },
  {
    categoryKey: "dokumentasi_foto",
    categoryLabel: "Dokumentasi Foto",
    subcategoryKey: "selected_photos",
    subcategoryLabel: "Selected Photos",
    outputTypes: ["drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Link folder kurasi foto terbaik",
  },
  {
    categoryKey: "dokumentasi_foto",
    categoryLabel: "Dokumentasi Foto",
    subcategoryKey: "dokumentasi_mentah",
    subcategoryLabel: "Dokumentasi Mentah",
    outputTypes: ["drive_link"],
    archiveDefault: true,
    referenceDefault: false,
    requiresFile: false,
    requiresSourceLink: true,
    sensitivity: "internal",
    notes: "Tautan folder foto RAW kamera",
  },

  // 8. Aset Desain
  {
    categoryKey: "aset_desain",
    categoryLabel: "Aset Desain",
    subcategoryKey: "logo",
    subcategoryLabel: "Logo",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Aset visual logo",
  },
  {
    categoryKey: "aset_desain",
    categoryLabel: "Aset Desain",
    subcategoryKey: "icon",
    subcategoryLabel: "Icon",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Custom icon set",
  },
  {
    categoryKey: "aset_desain",
    categoryLabel: "Aset Desain",
    subcategoryKey: "ilustrasi",
    subcategoryLabel: "Ilustrasi",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Custom illustration",
  },
  {
    categoryKey: "aset_desain",
    categoryLabel: "Aset Desain",
    subcategoryKey: "pattern",
    subcategoryLabel: "Pattern",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Pola background dekoratif",
  },
  {
    categoryKey: "aset_desain",
    categoryLabel: "Aset Desain",
    subcategoryKey: "background",
    subcategoryLabel: "Background",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Latar belakang grafis",
  },
  {
    categoryKey: "aset_desain",
    categoryLabel: "Aset Desain",
    subcategoryKey: "texture",
    subcategoryLabel: "Texture",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Tekstur pendukung visual",
  },
  {
    categoryKey: "aset_desain",
    categoryLabel: "Aset Desain",
    subcategoryKey: "font_pairing",
    subcategoryLabel: "Font Pairing",
    outputTypes: ["text", "image"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Guideline nama-nama font",
  },
  {
    categoryKey: "aset_desain",
    categoryLabel: "Aset Desain",
    subcategoryKey: "color_palette",
    subcategoryLabel: "Color Palette",
    outputTypes: ["image", "text"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Paduan hex warna",
  },
  {
    categoryKey: "aset_desain",
    categoryLabel: "Aset Desain",
    subcategoryKey: "template_canva",
    subcategoryLabel: "Template Canva",
    outputTypes: ["canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Tautan shareable template canva",
  },
  {
    categoryKey: "aset_desain",
    categoryLabel: "Aset Desain",
    subcategoryKey: "template_figma",
    subcategoryLabel: "Template Figma",
    outputTypes: ["figma_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Tautan figma file",
  },
  {
    categoryKey: "aset_desain",
    categoryLabel: "Aset Desain",
    subcategoryKey: "template_photoshop",
    subcategoryLabel: "Template Photoshop",
    outputTypes: ["drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Tautan file PSD di GDrive",
  },
  {
    categoryKey: "aset_desain",
    categoryLabel: "Aset Desain",
    subcategoryKey: "template_illustrator",
    subcategoryLabel: "Template Illustrator",
    outputTypes: ["drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Tautan file AI di GDrive",
  },
  {
    categoryKey: "aset_desain",
    categoryLabel: "Aset Desain",
    subcategoryKey: "mockup",
    subcategoryLabel: "Mockup",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Desain preview visual produk",
  },
  {
    categoryKey: "aset_desain",
    categoryLabel: "Aset Desain",
    subcategoryKey: "asset_drive",
    subcategoryLabel: "Asset Drive",
    outputTypes: ["drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Kumpulan link asset lengkap di Drive",
  },

  // 9. Perlengkapan dan Operasional
  {
    categoryKey: "perlengkapan_dan_operasional",
    categoryLabel: "Perlengkapan dan Operasional",
    subcategoryKey: "list_perlengkapan",
    subcategoryLabel: "List Perlengkapan",
    outputTypes: ["spreadsheet", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Checklist perlengkapan",
  },
  {
    categoryKey: "perlengkapan_dan_operasional",
    categoryLabel: "Perlengkapan dan Operasional",
    subcategoryKey: "inventaris_acara",
    subcategoryLabel: "Inventaris Acara",
    outputTypes: ["spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Catatan log barang inventaris",
  },
  {
    categoryKey: "perlengkapan_dan_operasional",
    categoryLabel: "Perlengkapan dan Operasional",
    subcategoryKey: "peminjaman_alat",
    subcategoryLabel: "Peminjaman Alat",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Surat pinjam alat",
  },
  {
    categoryKey: "perlengkapan_dan_operasional",
    categoryLabel: "Perlengkapan dan Operasional",
    subcategoryKey: "layout_ruangan",
    subcategoryLabel: "Layout Ruangan",
    outputTypes: ["image", "pdf", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Denah tata letak panggung/meja",
  },
  {
    categoryKey: "perlengkapan_dan_operasional",
    categoryLabel: "Perlengkapan dan Operasional",
    subcategoryKey: "denah_venue",
    subcategoryLabel: "Denah Venue",
    outputTypes: ["image", "pdf"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Peta lokasi ruangan/tempat",
  },
  {
    categoryKey: "perlengkapan_dan_operasional",
    categoryLabel: "Perlengkapan dan Operasional",
    subcategoryKey: "rundown_teknis",
    subcategoryLabel: "Rundown Teknis",
    outputTypes: ["pdf", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Rundown detail divisi acara & perlengkapan",
  },
  {
    categoryKey: "perlengkapan_dan_operasional",
    categoryLabel: "Perlengkapan dan Operasional",
    subcategoryKey: "cue_card",
    subcategoryLabel: "Cue Card",
    outputTypes: ["pdf", "document", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Kartu pemandu MC/operator",
  },
  {
    categoryKey: "perlengkapan_dan_operasional",
    categoryLabel: "Perlengkapan dan Operasional",
    subcategoryKey: "operator_notes",
    subcategoryLabel: "Operator Notes",
    outputTypes: ["pdf", "document", "text"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Catatan operator sound/slide",
  },
  {
    categoryKey: "perlengkapan_dan_operasional",
    categoryLabel: "Perlengkapan dan Operasional",
    subcategoryKey: "lighting_notes",
    subcategoryLabel: "Lighting Notes",
    outputTypes: ["pdf", "document", "text"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Catatan tata lampu",
  },
  {
    categoryKey: "perlengkapan_dan_operasional",
    categoryLabel: "Perlengkapan dan Operasional",
    subcategoryKey: "sound_notes",
    subcategoryLabel: "Sound Notes",
    outputTypes: ["pdf", "document", "text"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Catatan soundcheck",
  },

  // 10. Koordinasi dan Aktivitas Non-File
  {
    categoryKey: "koordinasi_dan_aktivitas_non_file",
    categoryLabel: "Koordinasi dan Aktivitas Non-File",
    subcategoryKey: "briefing",
    subcategoryLabel: "Briefing",
    outputTypes: ["activity_log", "text"],
    archiveDefault: "optional",
    referenceDefault: false,
    requiresFile: false,
    requiresSourceLink: false,
    sensitivity: "internal",
    notes: "Catatan koordinasi internal",
  },
  {
    categoryKey: "koordinasi_dan_aktivitas_non_file",
    categoryLabel: "Koordinasi dan Aktivitas Non-File",
    subcategoryKey: "koordinasi_sie_lain",
    subcategoryLabel: "Koordinasi Sie Lain",
    outputTypes: ["activity_log", "text"],
    archiveDefault: "optional",
    referenceDefault: false,
    requiresFile: false,
    requiresSourceLink: false,
    sensitivity: "internal",
    notes: "Catatan koordinasi lintas divisi",
  },
  {
    categoryKey: "koordinasi_dan_aktivitas_non_file",
    categoryLabel: "Koordinasi dan Aktivitas Non-File",
    subcategoryKey: "follow_up_pic",
    subcategoryLabel: "Follow-up PIC",
    outputTypes: ["activity_log", "text"],
    archiveDefault: "optional",
    referenceDefault: false,
    requiresFile: false,
    requiresSourceLink: false,
    sensitivity: "internal",
    notes: "Pantau progres tugas tim",
  },
  {
    categoryKey: "koordinasi_dan_aktivitas_non_file",
    categoryLabel: "Koordinasi dan Aktivitas Non-File",
    subcategoryKey: "rapat_internal",
    subcategoryLabel: "Rapat Internal",
    outputTypes: ["activity_log", "text"],
    archiveDefault: "optional",
    referenceDefault: false,
    requiresFile: false,
    requiresSourceLink: false,
    sensitivity: "internal",
    notes: "Catatan notula rapat internal",
  },
  {
    categoryKey: "koordinasi_dan_aktivitas_non_file",
    categoryLabel: "Koordinasi dan Aktivitas Non-File",
    subcategoryKey: "distribusi_tugas",
    subcategoryLabel: "Distribusi Tugas",
    outputTypes: ["activity_log", "text", "checklist"],
    archiveDefault: "optional",
    referenceDefault: false,
    requiresFile: false,
    requiresSourceLink: false,
    sensitivity: "internal",
    notes: "Plot penugasan",
  },
  {
    categoryKey: "koordinasi_dan_aktivitas_non_file",
    categoryLabel: "Koordinasi dan Aktivitas Non-File",
    subcategoryKey: "cek_kesiapan",
    subcategoryLabel: "Cek Kesiapan",
    outputTypes: ["activity_log", "text", "checklist"],
    archiveDefault: "optional",
    referenceDefault: false,
    requiresFile: false,
    requiresSourceLink: false,
    sensitivity: "internal",
    notes: "Pengecekan item",
  },
  {
    categoryKey: "koordinasi_dan_aktivitas_non_file",
    categoryLabel: "Koordinasi dan Aktivitas Non-File",
    subcategoryKey: "konfirmasi_vendor",
    subcategoryLabel: "Konfirmasi Vendor",
    outputTypes: ["activity_log", "text"],
    archiveDefault: "optional",
    referenceDefault: false,
    requiresFile: false,
    requiresSourceLink: false,
    sensitivity: "internal",
    notes: "Catatan konfirmasi vendor",
  },
  {
    categoryKey: "koordinasi_dan_aktivitas_non_file",
    categoryLabel: "Koordinasi dan Aktivitas Non-File",
    subcategoryKey: "konfirmasi_narasumber",
    subcategoryLabel: "Konfirmasi Narasumber",
    outputTypes: ["activity_log", "text"],
    archiveDefault: "optional",
    referenceDefault: false,
    requiresFile: false,
    requiresSourceLink: false,
    sensitivity: "internal",
    notes: "Catatan konfirmasi narasumber",
  },
  {
    categoryKey: "koordinasi_dan_aktivitas_non_file",
    categoryLabel: "Koordinasi dan Aktivitas Non-File",
    subcategoryKey: "reminder_internal",
    subcategoryLabel: "Reminder Internal",
    outputTypes: ["activity_log", "text"],
    archiveDefault: "optional",
    referenceDefault: false,
    requiresFile: false,
    requiresSourceLink: false,
    sensitivity: "internal",
    notes: "Reminder deadline",
  },
  {
    categoryKey: "koordinasi_dan_aktivitas_non_file",
    categoryLabel: "Koordinasi dan Aktivitas Non-File",
    subcategoryKey: "monitoring_progress",
    subcategoryLabel: "Monitoring Progress",
    outputTypes: ["activity_log", "text"],
    archiveDefault: "optional",
    referenceDefault: false,
    requiresFile: false,
    requiresSourceLink: false,
    sensitivity: "internal",
    notes: "Catatan pantauan progress",
  },
  {
    categoryKey: "koordinasi_dan_aktivitas_non_file",
    categoryLabel: "Koordinasi dan Aktivitas Non-File",
    subcategoryKey: "review_internal",
    subcategoryLabel: "Review Internal",
    outputTypes: ["activity_log", "text"],
    archiveDefault: "optional",
    referenceDefault: false,
    requiresFile: false,
    requiresSourceLink: false,
    sensitivity: "internal",
    notes: "Review pengerjaan",
  },
  {
    categoryKey: "koordinasi_dan_aktivitas_non_file",
    categoryLabel: "Koordinasi dan Aktivitas Non-File",
    subcategoryKey: "quality_control",
    subcategoryLabel: "Quality Control",
    outputTypes: ["activity_log", "text"],
    archiveDefault: "optional",
    referenceDefault: false,
    requiresFile: false,
    requiresSourceLink: false,
    sensitivity: "internal",
    notes: "QC kelayakan output",
  },

  // 11. Publikasi dan Media Sosial
  {
    categoryKey: "publikasi_dan_media_sosial",
    categoryLabel: "Publikasi dan Media Sosial",
    subcategoryKey: "jadwal_posting",
    subcategoryLabel: "Jadwal Posting",
    outputTypes: ["spreadsheet", "image", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Rencana upload konten",
  },
  {
    categoryKey: "publikasi_dan_media_sosial",
    categoryLabel: "Publikasi dan Media Sosial",
    subcategoryKey: "content_plan",
    subcategoryLabel: "Content Plan",
    outputTypes: ["spreadsheet", "document", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Konsep tulisan/visual konten",
  },
  {
    categoryKey: "publikasi_dan_media_sosial",
    categoryLabel: "Publikasi dan Media Sosial",
    subcategoryKey: "content_calendar",
    subcategoryLabel: "Content Calendar",
    outputTypes: ["spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Jadwal bulanan konten",
  },
  {
    categoryKey: "publikasi_dan_media_sosial",
    categoryLabel: "Publikasi dan Media Sosial",
    subcategoryKey: "draft_feed",
    subcategoryLabel: "Draft Feed",
    outputTypes: ["image", "canva_link", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Draft postingan feed",
  },
  {
    categoryKey: "publikasi_dan_media_sosial",
    categoryLabel: "Publikasi dan Media Sosial",
    subcategoryKey: "draft_story",
    subcategoryLabel: "Draft Story",
    outputTypes: ["image", "canva_link", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Draft postingan story",
  },
  {
    categoryKey: "publikasi_dan_media_sosial",
    categoryLabel: "Publikasi dan Media Sosial",
    subcategoryKey: "draft_reels",
    subcategoryLabel: "Draft Reels",
    outputTypes: ["video", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Draft postingan video pendek",
  },
  {
    categoryKey: "publikasi_dan_media_sosial",
    categoryLabel: "Publikasi dan Media Sosial",
    subcategoryKey: "caption_plan",
    subcategoryLabel: "Caption Plan",
    outputTypes: ["text", "document"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Teks caption postingan",
  },
  {
    categoryKey: "publikasi_dan_media_sosial",
    categoryLabel: "Publikasi dan Media Sosial",
    subcategoryKey: "hashtag_list",
    subcategoryLabel: "Hashtag List",
    outputTypes: ["text", "document"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Daftar hashtag relevan",
  },
  {
    categoryKey: "publikasi_dan_media_sosial",
    categoryLabel: "Publikasi dan Media Sosial",
    subcategoryKey: "media_partner_kit",
    subcategoryLabel: "Media Partner Kit",
    outputTypes: ["pdf", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Proposal/materi medpart",
  },
  {
    categoryKey: "publikasi_dan_media_sosial",
    categoryLabel: "Publikasi dan Media Sosial",
    subcategoryKey: "publikasi_final",
    subcategoryLabel: "Publikasi Final",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Tangkapan layar bukti postingan tayang",
  },
  {
    categoryKey: "publikasi_dan_media_sosial",
    categoryLabel: "Publikasi dan Media Sosial",
    subcategoryKey: "insight_report",
    subcategoryLabel: "Insight Report",
    outputTypes: ["pdf", "image", "spreadsheet"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Laporan performa pasca event",
  },

  // 12. Registrasi dan Peserta
  {
    categoryKey: "registrasi_dan_peserta",
    categoryLabel: "Registrasi dan Peserta",
    subcategoryKey: "form_pendaftaran",
    subcategoryLabel: "Form Pendaftaran",
    outputTypes: ["drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Link form registrasi online",
  },
  {
    categoryKey: "registrasi_dan_peserta",
    categoryLabel: "Registrasi dan Peserta",
    subcategoryKey: "header_google_form",
    subcategoryLabel: "Header Google Form",
    outputTypes: ["image", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Banner header form",
  },
  {
    categoryKey: "registrasi_dan_peserta",
    categoryLabel: "Registrasi dan Peserta",
    subcategoryKey: "rekap_pendaftar",
    subcategoryLabel: "Rekap Pendaftar",
    outputTypes: ["spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: false,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "sensitive",
    notes: "Rekap pendaftar (sensitif)",
  },
  {
    categoryKey: "registrasi_dan_peserta",
    categoryLabel: "Registrasi dan Peserta",
    subcategoryKey: "rekap_kehadiran",
    subcategoryLabel: "Rekap Kehadiran",
    outputTypes: ["spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: false,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "sensitive",
    notes: "Absensi kehadiran (sensitif)",
  },
  {
    categoryKey: "registrasi_dan_peserta",
    categoryLabel: "Registrasi dan Peserta",
    subcategoryKey: "sertifikat_peserta",
    subcategoryLabel: "Sertifikat Peserta",
    outputTypes: ["drive_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: false,
    requiresSourceLink: true,
    sensitivity: "normal",
    notes: "Drive folder sertifikat massal",
  },
  {
    categoryKey: "registrasi_dan_peserta",
    categoryLabel: "Registrasi dan Peserta",
    subcategoryKey: "e_ticket",
    subcategoryLabel: "E-ticket",
    outputTypes: ["pdf", "image", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Tiket masuk elektronik",
  },
  {
    categoryKey: "registrasi_dan_peserta",
    categoryLabel: "Registrasi dan Peserta",
    subcategoryKey: "kupon",
    subcategoryLabel: "Kupon",
    outputTypes: ["image", "pdf", "canva_link"],
    archiveDefault: true,
    referenceDefault: true,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "Kupon bazar/konsumsi",
  },
  {
    categoryKey: "registrasi_dan_peserta",
    categoryLabel: "Registrasi dan Peserta",
    subcategoryKey: "qr_code_peserta",
    subcategoryLabel: "QR Code Peserta",
    outputTypes: ["image", "drive_link"],
    archiveDefault: true,
    referenceDefault: "optional",
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "normal",
    notes: "QR check-in peserta",
  },
  {
    categoryKey: "registrasi_dan_peserta",
    categoryLabel: "Registrasi dan Peserta",
    subcategoryKey: "data_delegasi",
    subcategoryLabel: "Data Delegasi",
    outputTypes: ["spreadsheet", "drive_link"],
    archiveDefault: true,
    referenceDefault: false,
    requiresFile: true,
    requiresSourceLink: "optional",
    sensitivity: "sensitive",
    notes: "Data detail delegasi (sensitif)",
  },
];

export function getMainCategories() {
  return MAIN_CATEGORIES;
}

export function getSubcategories(categoryKey: string) {
  return CATEGORY_RULES.filter((rule) => rule.categoryKey === categoryKey).map((rule) => ({
    key: rule.subcategoryKey,
    label: rule.subcategoryLabel,
  }));
}

export function getCategoryRule(categoryKey: string, subcategoryKey: string): JobdeskCategoryRule | null {
  return CATEGORY_RULES.find((rule) => rule.categoryKey === categoryKey && rule.subcategoryKey === subcategoryKey) || null;
}

export function getDefaultArchiveSettings(categoryKey: string, subcategoryKey: string) {
  const rule = getCategoryRule(categoryKey, subcategoryKey);
  if (!rule) {
    return {
      archiveEnabled: true,
      referenceCandidateEnabled: false,
      requiresFile: false,
      requiresSourceLink: false,
      outputTypes: [] as string[],
      dataSensitivity: "normal" as const,
    };
  }
  return {
    archiveEnabled: rule.archiveDefault === true || rule.archiveDefault === "optional",
    referenceCandidateEnabled: rule.referenceDefault === true,
    requiresFile: rule.requiresFile === true,
    requiresSourceLink: rule.requiresSourceLink === true,
    outputTypes: rule.outputTypes,
    dataSensitivity: rule.sensitivity,
  };
}

type InferenceRule = {
  keyword: string;
  categoryKey: string;
  subcategoryKey: string;
  label: string;
};

export const INFERENCE_RULES: InferenceRule[] = [
  // Desain Publikasi
  { keyword: "countdown", categoryKey: "desain_publikasi", subcategoryKey: "countdown_design", label: "Countdown Design" },
  { keyword: "announcement", categoryKey: "desain_publikasi", subcategoryKey: "announcement_design", label: "Announcement Design" },
  { keyword: "thank you", categoryKey: "desain_publikasi", subcategoryKey: "thank_you_post", label: "Thank You Post" },
  { keyword: "reels cover", categoryKey: "desain_publikasi", subcategoryKey: "reels_cover", label: "Reels Cover" },
  { keyword: "thumbnail", categoryKey: "desain_publikasi", subcategoryKey: "thumbnail_video", label: "Thumbnail Video" },
  { keyword: "spanduk", categoryKey: "desain_publikasi", subcategoryKey: "spanduk_banner_cetak", label: "Spanduk / Banner Cetak" },
  { keyword: "x-banner", categoryKey: "desain_publikasi", subcategoryKey: "x_banner", label: "X-Banner" },
  { keyword: "baliho", categoryKey: "desain_publikasi", subcategoryKey: "baliho", label: "Baliho" },
  { keyword: "twibbon", categoryKey: "desain_publikasi", subcategoryKey: "twibbon", label: "Twibbon" },
  { keyword: "frame", categoryKey: "desain_publikasi", subcategoryKey: "frame_foto", label: "Frame Foto" },
  { keyword: "photobooth", categoryKey: "desain_publikasi", subcategoryKey: "photobooth", label: "Photobooth" },
  { keyword: "background zoom", categoryKey: "desain_publikasi", subcategoryKey: "background_zoom", label: "Background Zoom" },
  { keyword: "poster", categoryKey: "desain_publikasi", subcategoryKey: "poster", label: "Poster" },
  { keyword: "pamflet", categoryKey: "desain_publikasi", subcategoryKey: "pamflet", label: "Pamflet" },
  { keyword: "flyer", categoryKey: "desain_publikasi", subcategoryKey: "flyer", label: "Flyer" },
  { keyword: "feed", categoryKey: "desain_publikasi", subcategoryKey: "feed_instagram", label: "Feed Instagram" },
  { keyword: "story", categoryKey: "desain_publikasi", subcategoryKey: "story_instagram", label: "Story Instagram" },
  { keyword: "banner", categoryKey: "desain_publikasi", subcategoryKey: "spanduk_banner_cetak", label: "Spanduk / Banner Cetak" },

  // Identitas Acara dan Panitia
  { keyword: "brand guideline", categoryKey: "identitas_acara_dan_panitia", subcategoryKey: "brand_guideline_acara", label: "Brand Guideline Acara" },
  { keyword: "color palette", categoryKey: "identitas_acara_dan_panitia", subcategoryKey: "color_palette", label: "Color Palette" },
  { keyword: "palet warna", categoryKey: "identitas_acara_dan_panitia", subcategoryKey: "color_palette", label: "Color Palette" },
  { keyword: "kartu panitia", categoryKey: "identitas_acara_dan_panitia", subcategoryKey: "kartu_panitia", label: "Kartu Panitia" },
  { keyword: "kop surat", categoryKey: "identitas_acara_dan_panitia", subcategoryKey: "kop_surat_acara", label: "Kop Surat Acara" },
  { keyword: "logo acara", categoryKey: "identitas_acara_dan_panitia", subcategoryKey: "logo_acara", label: "Logo Acara" },
  { keyword: "name tag", categoryKey: "identitas_acara_dan_panitia", subcategoryKey: "name_tag", label: "Name Tag" },
  { keyword: "nametag", categoryKey: "identitas_acara_dan_panitia", subcategoryKey: "name_tag", label: "Name Tag" },
  { keyword: "id card", categoryKey: "identitas_acara_dan_panitia", subcategoryKey: "id_card", label: "ID Card" },
  { keyword: "badge", categoryKey: "identitas_acara_dan_panitia", subcategoryKey: "badge_peserta", label: "Badge Peserta" },
  { keyword: "sertifikat", categoryKey: "identitas_acara_dan_panitia", subcategoryKey: "sertifikat", label: "Sertifikat" },
  { keyword: "piagam", categoryKey: "identitas_acara_dan_panitia", subcategoryKey: "piagam", label: "Piagam" },
  { keyword: "plakat", categoryKey: "identitas_acara_dan_panitia", subcategoryKey: "plakat_design", label: "Plakat Design" },
  { keyword: "maskot", categoryKey: "identitas_acara_dan_panitia", subcategoryKey: "maskot_acara", label: "Maskot Acara" },
  { keyword: "supergraphic", categoryKey: "identitas_acara_dan_panitia", subcategoryKey: "supergraphic", label: "Supergraphic" },

  // Dokumen Administrasi
  { keyword: "cover proposal", categoryKey: "dokumen_administrasi", subcategoryKey: "cover_proposal", label: "Cover Proposal" },
  { keyword: "surat undangan", categoryKey: "dokumen_administrasi", subcategoryKey: "surat_undangan", label: "Surat Undangan" },
  { keyword: "surat permohonan", categoryKey: "dokumen_administrasi", subcategoryKey: "surat_permohonan", label: "Surat Permohonan" },
  { keyword: "surat tugas", categoryKey: "dokumen_administrasi", subcategoryKey: "surat_tugas", label: "Surat Tugas" },
  { keyword: "surat peminjaman", categoryKey: "dokumen_administrasi", subcategoryKey: "surat_peminjaman", label: "Surat Peminjaman" },
  { keyword: "surat dispensasi", categoryKey: "dokumen_administrasi", subcategoryKey: "surat_dispensasi", label: "Surat Dispensasi" },
  { keyword: "checklist perlengkapan", categoryKey: "dokumen_administrasi", subcategoryKey: "checklist_perlengkapan", label: "Checklist Perlengkapan" },
  { keyword: "daftar peserta", categoryKey: "dokumen_administrasi", subcategoryKey: "daftar_peserta", label: "Daftar Peserta" },
  { keyword: "buku panduan", categoryKey: "dokumen_administrasi", subcategoryKey: "buku_panduan", label: "Buku Panduan" },
  { keyword: "timeline", categoryKey: "dokumen_administrasi", subcategoryKey: "timeline_kerja", label: "Timeline Kerja" },
  { keyword: "sk panitia", categoryKey: "dokumen_administrasi", subcategoryKey: "sk_panitia", label: "SK Panitia" },
  { keyword: "proposal", categoryKey: "dokumen_administrasi", subcategoryKey: "proposal", label: "Proposal" },
  { keyword: "lpj", categoryKey: "dokumen_administrasi", subcategoryKey: "lpj", label: "LPJ" },
  { keyword: "notulen", categoryKey: "dokumen_administrasi", subcategoryKey: "notulen", label: "Notulen" },
  { keyword: "rundown", categoryKey: "dokumen_administrasi", subcategoryKey: "rundown", label: "Rundown" },
  { keyword: "tor", categoryKey: "dokumen_administrasi", subcategoryKey: "tor_term_of_reference", label: "TOR / Term of Reference" },
  { keyword: "juknis", categoryKey: "dokumen_administrasi", subcategoryKey: "juknis", label: "Juknis" },
  { keyword: "sop", categoryKey: "dokumen_administrasi", subcategoryKey: "sop", label: "SOP" },
  { keyword: "absensi", categoryKey: "dokumen_administrasi", subcategoryKey: "absensi", label: "Absensi" },

  // Keuangan dan Spreadsheet
  { keyword: "lpj keuangan", categoryKey: "keuangan_dan_spreadsheet", subcategoryKey: "lpj_keuangan", label: "LPJ Keuangan" },
  { keyword: "rekap pengeluaran", categoryKey: "keuangan_dan_spreadsheet", subcategoryKey: "rekap_pengeluaran", label: "Rekap Pengeluaran" },
  { keyword: "rekap pemasukan", categoryKey: "keuangan_dan_spreadsheet", subcategoryKey: "rekap_pemasukan", label: "Rekap Pemasukan" },
  { keyword: "bukti pembayaran", categoryKey: "keuangan_dan_spreadsheet", subcategoryKey: "bukti_pembayaran", label: "Bukti Pembayaran" },
  { keyword: "sponsorship", categoryKey: "keuangan_dan_spreadsheet", subcategoryKey: "sponsorship_sheet", label: "Sponsorship Sheet" },
  { keyword: "konsumsi sheet", categoryKey: "keuangan_dan_spreadsheet", subcategoryKey: "konsumsi_sheet", label: "Konsumsi Sheet" },
  { keyword: "transport sheet", categoryKey: "keuangan_dan_spreadsheet", subcategoryKey: "transport_sheet", label: "Transport Sheet" },
  { keyword: "merchandise sheet", categoryKey: "keuangan_dan_spreadsheet", subcategoryKey: "merchandise_sheet", label: "Merchandise Sheet" },
  { keyword: "rab", categoryKey: "keuangan_dan_spreadsheet", subcategoryKey: "rab", label: "RAB" },
  { keyword: "invoice", categoryKey: "keuangan_dan_spreadsheet", subcategoryKey: "invoice", label: "Invoice" },
  { keyword: "kwitansi", categoryKey: "keuangan_dan_spreadsheet", subcategoryKey: "kwitansi", label: "Kwitansi" },

  // Konten dan Copywriting
  { keyword: "copy poster", categoryKey: "konten_dan_copywriting", subcategoryKey: "copy_poster", label: "Copy Poster" },
  { keyword: "press release", categoryKey: "konten_dan_copywriting", subcategoryKey: "press_release", label: "Press Release" },
  { keyword: "narasi mc", categoryKey: "konten_dan_copywriting", subcategoryKey: "narasi_mc", label: "Narasi MC" },
  { keyword: "script voice over", categoryKey: "konten_dan_copywriting", subcategoryKey: "script_voice_over", label: "Script Voice Over" },
  { keyword: "script video", categoryKey: "konten_dan_copywriting", subcategoryKey: "script_video", label: "Script Video" },
  { keyword: "reminder text", categoryKey: "konten_dan_copywriting", subcategoryKey: "reminder_text", label: "Reminder Text" },
  { keyword: "template email", categoryKey: "konten_dan_copywriting", subcategoryKey: "template_email", label: "Template Email" },
  { keyword: "caption", categoryKey: "konten_dan_copywriting", subcategoryKey: "caption_instagram", label: "Caption Instagram" },
  { keyword: "sambutan", categoryKey: "konten_dan_copywriting", subcategoryKey: "sambutan", label: "Sambutan" },
  { keyword: "broadcast", categoryKey: "konten_dan_copywriting", subcategoryKey: "broadcast_message", label: "Broadcast Message" },

  // Video dan Multimedia
  { keyword: "dokumentasi video", categoryKey: "video_dan_multimedia", subcategoryKey: "video_dokumentasi", label: "Video Dokumentasi" },
  { keyword: "video opening", categoryKey: "video_dan_multimedia", subcategoryKey: "video_opening", label: "Video Opening" },
  { keyword: "motion graphic", categoryKey: "video_dan_multimedia", subcategoryKey: "motion_graphic", label: "Motion Graphic" },
  { keyword: "lower third", categoryKey: "video_dan_multimedia", subcategoryKey: "lower_third", label: "Lower Third" },
  { keyword: "teaser", categoryKey: "video_dan_multimedia", subcategoryKey: "video_teaser", label: "Video Teaser" },
  { keyword: "highlight", categoryKey: "video_dan_multimedia", subcategoryKey: "video_highlight", label: "Video Highlight" },
  { keyword: "aftermovie", categoryKey: "video_dan_multimedia", subcategoryKey: "video_aftermovie", label: "Video Aftermovie" },
  { keyword: "bumper", categoryKey: "video_dan_multimedia", subcategoryKey: "video_bumper", label: "Video Bumper" },
  { keyword: "testimoni", categoryKey: "video_dan_multimedia", subcategoryKey: "video_testimoni", label: "Video Testimoni" },
  { keyword: "subtitle", categoryKey: "video_dan_multimedia", subcategoryKey: "subtitle_file", label: "Subtitle File" },
  { keyword: "backsound", categoryKey: "video_dan_multimedia", subcategoryKey: "audio_backsound", label: "Audio Backsound" },
  { keyword: "voice over", categoryKey: "video_dan_multimedia", subcategoryKey: "voice_over", label: "Voice Over" },

  // Dokumentasi Foto
  { keyword: "foto dokumentasi", categoryKey: "dokumentasi_foto", subcategoryKey: "foto_dokumentasi", label: "Foto Dokumentasi" },
  { keyword: "foto panitia", categoryKey: "dokumentasi_foto", subcategoryKey: "foto_panitia", label: "Foto Panitia" },
  { keyword: "foto peserta", categoryKey: "dokumentasi_foto", subcategoryKey: "foto_peserta", label: "Foto Peserta" },
  { keyword: "foto narasumber", categoryKey: "dokumentasi_foto", subcategoryKey: "foto_narasumber", label: "Foto Narasumber" },
  { keyword: "foto venue", categoryKey: "dokumentasi_foto", subcategoryKey: "foto_venue", label: "Foto Venue" },
  { keyword: "behind the scene", categoryKey: "dokumentasi_foto", subcategoryKey: "foto_behind_the_scene", label: "Foto Behind The Scene" },
  { keyword: "selected photos", categoryKey: "dokumentasi_foto", subcategoryKey: "selected_photos", label: "Selected Photos" },
  { keyword: "dokumentasi mentah", categoryKey: "dokumentasi_foto", subcategoryKey: "dokumentasi_mentah", label: "Dokumentasi Mentah" },

  // Aset Desain
  { keyword: "template canva", categoryKey: "aset_desain", subcategoryKey: "template_canva", label: "Template Canva" },
  { keyword: "template figma", categoryKey: "aset_desain", subcategoryKey: "template_figma", label: "Template Figma" },
  { keyword: "template photoshop", categoryKey: "aset_desain", subcategoryKey: "template_photoshop", label: "Template Photoshop" },
  { keyword: "template illustrator", categoryKey: "aset_desain", subcategoryKey: "template_illustrator", label: "Template Illustrator" },
  { keyword: "font pairing", categoryKey: "aset_desain", subcategoryKey: "font_pairing", label: "Font Pairing" },
  { keyword: "aset desain", categoryKey: "aset_desain", subcategoryKey: "asset_drive", label: "Asset Drive" },
  { keyword: "mockup", categoryKey: "aset_desain", subcategoryKey: "mockup", label: "Mockup" },
  { keyword: "pattern", categoryKey: "aset_desain", subcategoryKey: "pattern", label: "Pattern" },
  { keyword: "background", categoryKey: "aset_desain", subcategoryKey: "background", label: "Background" },
  { keyword: "texture", categoryKey: "aset_desain", subcategoryKey: "texture", label: "Texture" },

  // Perlengkapan dan Operasional
  { keyword: "list perlengkapan", categoryKey: "perlengkapan_dan_operasional", subcategoryKey: "list_perlengkapan", label: "List Perlengkapan" },
  { keyword: "peminjaman alat", categoryKey: "perlengkapan_dan_operasional", subcategoryKey: "peminjaman_alat", label: "Peminjaman Alat" },
  { keyword: "layout ruangan", categoryKey: "perlengkapan_dan_operasional", subcategoryKey: "layout_ruangan", label: "Layout Ruangan" },
  { keyword: "denah venue", categoryKey: "perlengkapan_dan_operasional", subcategoryKey: "denah_venue", label: "Denah Venue" },
  { keyword: "rundown teknis", categoryKey: "perlengkapan_dan_operasional", subcategoryKey: "rundown_teknis", label: "Rundown Teknis" },
  { keyword: "cue card", categoryKey: "perlengkapan_dan_operasional", subcategoryKey: "cue_card", label: "Cue Card" },
  { keyword: "operator notes", categoryKey: "perlengkapan_dan_operasional", subcategoryKey: "operator_notes", label: "Operator Notes" },
  { keyword: "lighting notes", categoryKey: "perlengkapan_dan_operasional", subcategoryKey: "lighting_notes", label: "Lighting Notes" },
  { keyword: "sound notes", categoryKey: "perlengkapan_dan_operasional", subcategoryKey: "sound_notes", label: "Sound Notes" },
  { keyword: "inventaris", categoryKey: "perlengkapan_dan_operasional", subcategoryKey: "inventaris_acara", label: "Inventaris Acara" },

  // Koordinasi dan Aktivitas Non-File
  { keyword: "distribusi tugas", categoryKey: "koordinasi_dan_aktivitas_non_file", subcategoryKey: "distribusi_tugas", label: "Distribusi Tugas" },
  { keyword: "cek kesiapan", categoryKey: "koordinasi_dan_aktivitas_non_file", subcategoryKey: "cek_kesiapan", label: "Cek Kesiapan" },
  { keyword: "konfirmasi vendor", categoryKey: "koordinasi_dan_aktivitas_non_file", subcategoryKey: "konfirmasi_vendor", label: "Konfirmasi Vendor" },
  { keyword: "konfirmasi narasumber", categoryKey: "koordinasi_dan_aktivitas_non_file", subcategoryKey: "konfirmasi_narasumber", label: "Konfirmasi Narasumber" },
  { keyword: "monitoring progress", categoryKey: "koordinasi_dan_aktivitas_non_file", subcategoryKey: "monitoring_progress", label: "Monitoring Progress" },
  { keyword: "review internal", categoryKey: "koordinasi_dan_aktivitas_non_file", subcategoryKey: "review_internal", label: "Review Internal" },
  { keyword: "quality control", categoryKey: "koordinasi_dan_aktivitas_non_file", subcategoryKey: "quality_control", label: "Quality Control" },
  { keyword: "briefing", categoryKey: "koordinasi_dan_aktivitas_non_file", subcategoryKey: "briefing", label: "Briefing" },
  { keyword: "koordinasi", categoryKey: "koordinasi_dan_aktivitas_non_file", subcategoryKey: "koordinasi_sie_lain", label: "Koordinasi Sie Lain" },
  { keyword: "follow-up", categoryKey: "koordinasi_dan_aktivitas_non_file", subcategoryKey: "follow_up_pic", label: "Follow-up PIC" },
  { keyword: "rapat", categoryKey: "koordinasi_dan_aktivitas_non_file", subcategoryKey: "rapat_internal", label: "Rapat Internal" },

  // Publikasi dan Media Sosial
  { keyword: "jadwal posting", categoryKey: "publikasi_dan_media_sosial", subcategoryKey: "jadwal_posting", label: "Jadwal Posting" },
  { keyword: "content plan", categoryKey: "publikasi_dan_media_sosial", subcategoryKey: "content_plan", label: "Content Plan" },
  { keyword: "content calendar", categoryKey: "publikasi_dan_media_sosial", subcategoryKey: "content_calendar", label: "Content Calendar" },
  { keyword: "draft feed", categoryKey: "publikasi_dan_media_sosial", subcategoryKey: "draft_feed", label: "Draft Feed" },
  { keyword: "draft story", categoryKey: "publikasi_dan_media_sosial", subcategoryKey: "draft_story", label: "Draft Story" },
  { keyword: "draft reels", categoryKey: "publikasi_dan_media_sosial", subcategoryKey: "draft_reels", label: "Draft Reels" },
  { keyword: "caption plan", categoryKey: "publikasi_dan_media_sosial", subcategoryKey: "caption_plan", label: "Caption Plan" },
  { keyword: "hashtag", categoryKey: "publikasi_dan_media_sosial", subcategoryKey: "hashtag_list", label: "Hashtag List" },
  { keyword: "media partner", categoryKey: "publikasi_dan_media_sosial", subcategoryKey: "media_partner_kit", label: "Media Partner Kit" },
  { keyword: "publikasi final", categoryKey: "publikasi_dan_media_sosial", subcategoryKey: "publikasi_final", label: "Publikasi Final" },
  { keyword: "insight report", categoryKey: "publikasi_dan_media_sosial", subcategoryKey: "insight_report", label: "Insight Report" },

  // Registrasi dan Peserta
  { keyword: "form pendaftaran", categoryKey: "registrasi_dan_peserta", subcategoryKey: "form_pendaftaran", label: "Form Pendaftaran" },
  { keyword: "header google form", categoryKey: "registrasi_dan_peserta", subcategoryKey: "header_google_form", label: "Header Google Form" },
  { keyword: "rekap pendaftar", categoryKey: "registrasi_dan_peserta", subcategoryKey: "rekap_pendaftar", label: "Rekap Pendaftar" },
  { keyword: "rekap kehadiran", categoryKey: "registrasi_dan_peserta", subcategoryKey: "rekap_kehadiran", label: "Rekap Kehadiran" },
  { keyword: "sertifikat peserta", categoryKey: "registrasi_dan_peserta", subcategoryKey: "sertifikat_peserta", label: "Sertifikat Peserta" },
  { keyword: "e-ticket", categoryKey: "registrasi_dan_peserta", subcategoryKey: "e_ticket", label: "E-ticket" },
  { keyword: "kupon", categoryKey: "registrasi_dan_peserta", subcategoryKey: "kupon", label: "Kupon" },
  { keyword: "qr code peserta", categoryKey: "registrasi_dan_peserta", subcategoryKey: "qr_code_peserta", label: "QR Code Peserta" },
  { keyword: "data delegasi", categoryKey: "registrasi_dan_peserta", subcategoryKey: "data_delegasi", label: "Data Delegasi" }
];

export function inferJobdeskCategoryFromText(input: {
  title?: string;
  description?: string;
  existingCategoryKey?: string;
  existingSubcategoryKey?: string;
}): {
  categoryKey: string;
  subcategoryKey: string;
  confidence: "high" | "medium" | "low";
  reason: string;
} | null {
  if (input.existingCategoryKey && input.existingSubcategoryKey) {
    return null; // Already has category, don't override
  }

  const titleLower = (input.title || "").toLowerCase();
  const descLower = (input.description || "").toLowerCase();

  // Try title first (High confidence)
  for (const rule of INFERENCE_RULES) {
    if (titleLower.includes(rule.keyword)) {
      return {
        categoryKey: rule.categoryKey,
        subcategoryKey: rule.subcategoryKey,
        confidence: "high",
        reason: `Terdeteksi dari kata '${rule.keyword}' pada judul jobdesk.`,
      };
    }
  }

  // Try description (Medium confidence)
  for (const rule of INFERENCE_RULES) {
    if (descLower.includes(rule.keyword)) {
      return {
        categoryKey: rule.categoryKey,
        subcategoryKey: rule.subcategoryKey,
        confidence: "medium",
        reason: `Terdeteksi dari kata '${rule.keyword}' pada deskripsi jobdesk.`,
      };
    }
  }

  return null;
}
